<?php
include 'header.php';
?>
<div style="margin-top: 45px; margin-left: 20px">
<p><strong>Free&nbsp;website&nbsp;terms&nbsp;and&nbsp;conditions:&nbsp;cover&nbsp;sheet</strong></p>
<p><strong>SEQ&nbsp;Legal&nbsp;LLP</strong></p>
<ol>
<li>This&nbsp;template&nbsp;legal&nbsp;document&nbsp;was&nbsp;produced&nbsp;and&nbsp;published&nbsp;by&nbsp;SEQ&nbsp;Legal&nbsp;LLP.</li>
<li>We&nbsp;control&nbsp;the&nbsp;copyright&nbsp;in&nbsp;this&nbsp;template,&nbsp;and&nbsp;you&nbsp;may&nbsp;only&nbsp;use&nbsp;this&nbsp;template&nbsp;in&nbsp;accordance&nbsp;with&nbsp;the&nbsp;licensing&nbsp;provisions&nbsp;in&nbsp;our&nbsp;terms&nbsp;and&nbsp;conditions.&nbsp;Those&nbsp;licensing&nbsp;provisions&nbsp;include&nbsp;an&nbsp;obligation&nbsp;to&nbsp;retain&nbsp;the&nbsp;SEQ&nbsp;Legal&nbsp;credit&nbsp;incorporated&nbsp;into&nbsp;the&nbsp;template.</li>
<li>The&nbsp;current&nbsp;version&nbsp;of&nbsp;our&nbsp;terms&nbsp;and&nbsp;conditions&nbsp;is&nbsp;available&nbsp;at:&nbsp;http://www.seqlegal.com/our-terms-and-conditions.</li>
<li>If&nbsp;you&nbsp;would&nbsp;like&nbsp;to&nbsp;use&nbsp;this&nbsp;template&nbsp;without&nbsp;the&nbsp;SEQ&nbsp;Legal&nbsp;credit,&nbsp;you&nbsp;can&nbsp;purchase&nbsp;a&nbsp;licence&nbsp;to&nbsp;do&nbsp;so&nbsp;at:&nbsp;http://www.website-contracts.co.uk.</li>
<li>You&nbsp;will&nbsp;need&nbsp;to&nbsp;edit&nbsp;this&nbsp;template&nbsp;before&nbsp;use.&nbsp;Guidance&nbsp;notes&nbsp;to&nbsp;help&nbsp;you&nbsp;do&nbsp;so&nbsp;are&nbsp;set&nbsp;out&nbsp;at&nbsp;the&nbsp;end&nbsp;of&nbsp;the&nbsp;template.&nbsp;During&nbsp;the&nbsp;editing&nbsp;process,&nbsp;you&nbsp;should&nbsp;delete&nbsp;those&nbsp;guidance&nbsp;notes&nbsp;and&nbsp;this&nbsp;cover&nbsp;sheet.&nbsp;Square&nbsp;brackets&nbsp;in&nbsp;the&nbsp;body&nbsp;of&nbsp;the&nbsp;document&nbsp;indicate&nbsp;areas&nbsp;that&nbsp;require&nbsp;editorial&nbsp;attention.&nbsp;By&nbsp;the&nbsp;end&nbsp;of&nbsp;the&nbsp;editing&nbsp;process,&nbsp;there&nbsp;should&nbsp;be&nbsp;no&nbsp;square&nbsp;brackets&nbsp;left&nbsp;in&nbsp;the&nbsp;body&nbsp;of&nbsp;the&nbsp;document.</li>
<li>If&nbsp;you&nbsp;have&nbsp;any&nbsp;doubts&nbsp;about&nbsp;the&nbsp;editing&nbsp;or&nbsp;use&nbsp;of&nbsp;this&nbsp;template,&nbsp;you&nbsp;should&nbsp;seek&nbsp;professional&nbsp;legal&nbsp;advice.</li>
<li>You&nbsp;may&nbsp;be&nbsp;able&nbsp;to&nbsp;get&nbsp;free&nbsp;legal&nbsp;guidance&nbsp;using&nbsp;our&nbsp;public&nbsp;Q&amp;A&nbsp;system,&nbsp;available&nbsp;at:&nbsp;http://www.seqlegal.com/questions.&nbsp;</li>
<li>You&nbsp;can&nbsp;request&nbsp;a&nbsp;quote&nbsp;for&nbsp;legal&nbsp;services&nbsp;(including&nbsp;the&nbsp;adaptation&nbsp;or&nbsp;review&nbsp;of&nbsp;a&nbsp;legal&nbsp;document&nbsp;produced&nbsp;from&nbsp;this&nbsp;template)&nbsp;using&nbsp;this&nbsp;form:&nbsp;http://www.seqlegal.com/request-quote.</li>
</ol>
<p>&nbsp;</p>
<p><strong>Terms&nbsp;and&nbsp;conditions&nbsp;of&nbsp;use</strong></p>
<ol>
<li><strong>Introduction</strong></li>
</ol>
<p>1.1These&nbsp;terms&nbsp;and&nbsp;conditions&nbsp;shall&nbsp;govern&nbsp;your&nbsp;use&nbsp;of&nbsp;our&nbsp;website.</p>
<p>1.2By&nbsp;using&nbsp;our&nbsp;website,&nbsp;you&nbsp;accept&nbsp;these&nbsp;terms&nbsp;and&nbsp;conditions&nbsp;in&nbsp;full;&nbsp;accordingly,&nbsp;if&nbsp;you&nbsp;disagree&nbsp;with&nbsp;these&nbsp;terms&nbsp;and&nbsp;conditions&nbsp;or&nbsp;any&nbsp;part&nbsp;of&nbsp;these&nbsp;terms&nbsp;and&nbsp;conditions,&nbsp;you&nbsp;must&nbsp;not&nbsp;use&nbsp;our&nbsp;website.</p>
<p>1.3If&nbsp;you&nbsp;[register&nbsp;with&nbsp;our&nbsp;website,&nbsp;submit&nbsp;any&nbsp;material&nbsp;to&nbsp;our&nbsp;website&nbsp;or&nbsp;use&nbsp;any&nbsp;of&nbsp;our&nbsp;website&nbsp;services],&nbsp;we&nbsp;will&nbsp;ask&nbsp;you&nbsp;to&nbsp;expressly&nbsp;agree&nbsp;to&nbsp;these&nbsp;terms&nbsp;and&nbsp;conditions.</p>
<p>1.4[You&nbsp;must&nbsp;be&nbsp;at&nbsp;least&nbsp;[18]&nbsp;years&nbsp;of&nbsp;age&nbsp;to&nbsp;use&nbsp;our&nbsp;website;&nbsp;and&nbsp;by&nbsp;using&nbsp;our&nbsp;website&nbsp;or&nbsp;agreeing&nbsp;to&nbsp;these&nbsp;terms&nbsp;and&nbsp;conditions,&nbsp;you&nbsp;warrant&nbsp;and&nbsp;represent&nbsp;to&nbsp;us&nbsp;that&nbsp;you&nbsp;are&nbsp;at&nbsp;least&nbsp;[18]&nbsp;years&nbsp;of&nbsp;age.]</p>
<p>1.5[Our&nbsp;website&nbsp;uses&nbsp;cookies;&nbsp;by&nbsp;using&nbsp;our&nbsp;website&nbsp;or&nbsp;agreeing&nbsp;to&nbsp;these&nbsp;terms&nbsp;and&nbsp;conditions,&nbsp;you&nbsp;consent&nbsp;to&nbsp;our&nbsp;use&nbsp;of&nbsp;cookies&nbsp;in&nbsp;accordance&nbsp;with&nbsp;the&nbsp;terms&nbsp;of&nbsp;our&nbsp;[privacy&nbsp;and&nbsp;cookies&nbsp;policy].]</p>
<ol start="2">
<li><strong>Credit</strong></li>
</ol>
<p>2.1This&nbsp;document&nbsp;was&nbsp;created&nbsp;using&nbsp;a&nbsp;template&nbsp;from&nbsp;<a href="http://www.seqlegal.com">SEQ&nbsp;Legal</a>&nbsp;(http://www.seqlegal.com).</p>
<ol start="3">
<li><strong>Copyright&nbsp;notice</strong></li>
</ol>
<p>3.1Copyright&nbsp;(c)&nbsp;[<em>year(s)&nbsp;of&nbsp;first&nbsp;publication</em>]&nbsp;[<em>full&nbsp;name</em>].</p>
<p>3.2Subject&nbsp;to&nbsp;the&nbsp;express&nbsp;provisions&nbsp;of&nbsp;these&nbsp;terms&nbsp;and&nbsp;conditions:</p>
<p>(a)we,&nbsp;together&nbsp;with&nbsp;our&nbsp;licensors,&nbsp;own&nbsp;and&nbsp;control&nbsp;all&nbsp;the&nbsp;copyright&nbsp;and&nbsp;other&nbsp;intellectual&nbsp;property&nbsp;rights&nbsp;in&nbsp;our&nbsp;website&nbsp;and&nbsp;the&nbsp;material&nbsp;on&nbsp;our&nbsp;website;&nbsp;and</p>
<p>(b)all&nbsp;the&nbsp;copyright&nbsp;and&nbsp;other&nbsp;intellectual&nbsp;property&nbsp;rights&nbsp;in&nbsp;our&nbsp;website&nbsp;and&nbsp;the&nbsp;material&nbsp;on&nbsp;our&nbsp;website&nbsp;are&nbsp;reserved.</p>
<ol start="4">
<li><strong>Licence&nbsp;to&nbsp;use&nbsp;website</strong></li>
</ol>
<p>4.1You&nbsp;may:</p>
<p>(a)view&nbsp;pages&nbsp;from&nbsp;our&nbsp;website&nbsp;in&nbsp;a&nbsp;web&nbsp;browser;</p>
<p>(b)download&nbsp;pages&nbsp;from&nbsp;our&nbsp;website&nbsp;for&nbsp;caching&nbsp;in&nbsp;a&nbsp;web&nbsp;browser;</p>
<p>(c)print&nbsp;pages&nbsp;from&nbsp;our&nbsp;website;</p>
<p>(d)[stream&nbsp;audio&nbsp;and&nbsp;video&nbsp;files&nbsp;from&nbsp;our&nbsp;website;&nbsp;and]</p>
<p>(e)[use&nbsp;[our&nbsp;website&nbsp;services]&nbsp;by&nbsp;means&nbsp;of&nbsp;a&nbsp;web&nbsp;browser,]</p>
<p>subject&nbsp;to&nbsp;the&nbsp;other&nbsp;provisions&nbsp;of&nbsp;these&nbsp;terms&nbsp;and&nbsp;conditions.</p>
<p>4.2Except&nbsp;as&nbsp;expressly&nbsp;permitted&nbsp;by&nbsp;Section&nbsp;4.1&nbsp;or&nbsp;the&nbsp;other&nbsp;provisions&nbsp;of&nbsp;these&nbsp;terms&nbsp;and&nbsp;conditions,&nbsp;you&nbsp;must&nbsp;not&nbsp;download&nbsp;any&nbsp;material&nbsp;from&nbsp;our&nbsp;website&nbsp;or&nbsp;save&nbsp;any&nbsp;such&nbsp;material&nbsp;to&nbsp;your&nbsp;computer.</p>
<p>4.3[You&nbsp;may&nbsp;only&nbsp;use&nbsp;our&nbsp;website&nbsp;for&nbsp;[your&nbsp;own&nbsp;personal&nbsp;and&nbsp;business&nbsp;purposes],&nbsp;and&nbsp;you&nbsp;must&nbsp;not&nbsp;use&nbsp;our&nbsp;website&nbsp;for&nbsp;any&nbsp;other&nbsp;purposes.]</p>
<p>4.4Except&nbsp;as&nbsp;expressly&nbsp;permitted&nbsp;by&nbsp;these&nbsp;terms&nbsp;and&nbsp;conditions,&nbsp;you&nbsp;must&nbsp;not&nbsp;edit&nbsp;or&nbsp;otherwise&nbsp;modify&nbsp;any&nbsp;material&nbsp;on&nbsp;our&nbsp;website.</p>
<p>4.5Unless&nbsp;you&nbsp;own&nbsp;or&nbsp;control&nbsp;the&nbsp;relevant&nbsp;rights&nbsp;in&nbsp;the&nbsp;material,&nbsp;you&nbsp;must&nbsp;not:</p>
<p>(a)republish&nbsp;material&nbsp;from&nbsp;our&nbsp;website&nbsp;(including&nbsp;republication&nbsp;on&nbsp;another&nbsp;website);</p>
<p>(b)sell,&nbsp;rent&nbsp;or&nbsp;sub-license&nbsp;material&nbsp;from&nbsp;our&nbsp;website;</p>
<p>(c)show&nbsp;any&nbsp;material&nbsp;from&nbsp;our&nbsp;website&nbsp;in&nbsp;public;</p>
<p>(d)exploit&nbsp;material&nbsp;from&nbsp;our&nbsp;website&nbsp;for&nbsp;a&nbsp;commercial&nbsp;purpose;&nbsp;or</p>
<p>(e)redistribute&nbsp;material&nbsp;from&nbsp;our&nbsp;website.</p>
<p>4.6[Notwithstanding&nbsp;Section&nbsp;4.5,&nbsp;you&nbsp;may&nbsp;redistribute&nbsp;[our&nbsp;newsletter]&nbsp;in&nbsp;[print&nbsp;and&nbsp;electronic&nbsp;form]&nbsp;to&nbsp;[any&nbsp;person].]</p>
<p>4.7We&nbsp;reserve&nbsp;the&nbsp;right&nbsp;to&nbsp;restrict&nbsp;access&nbsp;to&nbsp;areas&nbsp;of&nbsp;our&nbsp;website,&nbsp;or&nbsp;indeed&nbsp;our&nbsp;whole&nbsp;website,&nbsp;at&nbsp;our&nbsp;discretion;&nbsp;you&nbsp;must&nbsp;not&nbsp;circumvent&nbsp;or&nbsp;bypass,&nbsp;or&nbsp;attempt&nbsp;to&nbsp;circumvent&nbsp;or&nbsp;bypass,&nbsp;any&nbsp;access&nbsp;restriction&nbsp;measures&nbsp;on&nbsp;our&nbsp;website.</p>
<ol start="5">
<li><strong>Acceptable&nbsp;use</strong></li>
</ol>
<p>5.1You&nbsp;must&nbsp;not:</p>
<p>(a)use&nbsp;our&nbsp;website&nbsp;in&nbsp;any&nbsp;way&nbsp;or&nbsp;take&nbsp;any&nbsp;action&nbsp;that&nbsp;causes,&nbsp;or&nbsp;may&nbsp;cause,&nbsp;damage&nbsp;to&nbsp;the&nbsp;website&nbsp;or&nbsp;impairment&nbsp;of&nbsp;the&nbsp;performance,&nbsp;availability&nbsp;or&nbsp;accessibility&nbsp;of&nbsp;the&nbsp;website;</p>
<p>(b)use&nbsp;our&nbsp;website&nbsp;in&nbsp;any&nbsp;way&nbsp;that&nbsp;is&nbsp;unlawful,&nbsp;illegal,&nbsp;fraudulent&nbsp;or&nbsp;harmful,&nbsp;or&nbsp;in&nbsp;connection&nbsp;with&nbsp;any&nbsp;unlawful,&nbsp;illegal,&nbsp;fraudulent&nbsp;or&nbsp;harmful&nbsp;purpose&nbsp;or&nbsp;activity;</p>
<p>(c)use&nbsp;our&nbsp;website&nbsp;to&nbsp;copy,&nbsp;store,&nbsp;host,&nbsp;transmit,&nbsp;send,&nbsp;use,&nbsp;publish&nbsp;or&nbsp;distribute&nbsp;any&nbsp;material&nbsp;which&nbsp;consists&nbsp;of&nbsp;(or&nbsp;is&nbsp;linked&nbsp;to)&nbsp;any&nbsp;spyware,&nbsp;computer&nbsp;virus,&nbsp;Trojan&nbsp;horse,&nbsp;worm,&nbsp;keystroke&nbsp;logger,&nbsp;rootkit&nbsp;or&nbsp;other&nbsp;malicious&nbsp;computer&nbsp;software;</p>
<p>(d)conduct&nbsp;any&nbsp;systematic&nbsp;or&nbsp;automated&nbsp;data&nbsp;collection&nbsp;activities&nbsp;(including&nbsp;without&nbsp;limitation&nbsp;scraping,&nbsp;data&nbsp;mining,&nbsp;data&nbsp;extraction&nbsp;and&nbsp;data&nbsp;harvesting)&nbsp;on&nbsp;or&nbsp;in&nbsp;relation&nbsp;to&nbsp;our&nbsp;website&nbsp;without&nbsp;our&nbsp;express&nbsp;written&nbsp;consent;</p>
<p>(e)[access&nbsp;or&nbsp;otherwise&nbsp;interact&nbsp;with&nbsp;our&nbsp;website&nbsp;using&nbsp;any&nbsp;robot,&nbsp;spider&nbsp;or&nbsp;other&nbsp;automated&nbsp;means;]</p>
<p>(f)[violate&nbsp;the&nbsp;directives&nbsp;set&nbsp;out&nbsp;in&nbsp;the&nbsp;robots.txt&nbsp;file&nbsp;for&nbsp;our&nbsp;website;&nbsp;or]</p>
<p>(g)[use&nbsp;data&nbsp;collected&nbsp;from&nbsp;our&nbsp;website&nbsp;for&nbsp;any&nbsp;direct&nbsp;marketing&nbsp;activity&nbsp;(including&nbsp;without&nbsp;limitation&nbsp;email&nbsp;marketing,&nbsp;SMS&nbsp;marketing,&nbsp;telemarketing&nbsp;and&nbsp;direct&nbsp;mailing).]</p>
<p>5.2[You&nbsp;must&nbsp;not&nbsp;use&nbsp;data&nbsp;collected&nbsp;from&nbsp;our&nbsp;website&nbsp;to&nbsp;contact&nbsp;individuals,&nbsp;companies&nbsp;or&nbsp;other&nbsp;persons&nbsp;or&nbsp;entities.]</p>
<p>5.3You&nbsp;must&nbsp;ensure&nbsp;that&nbsp;all&nbsp;the&nbsp;information&nbsp;you&nbsp;supply&nbsp;to&nbsp;us&nbsp;through&nbsp;our&nbsp;website,&nbsp;or&nbsp;in&nbsp;relation&nbsp;to&nbsp;our&nbsp;website,&nbsp;is&nbsp;[true,&nbsp;accurate,&nbsp;current,&nbsp;complete&nbsp;and&nbsp;non-misleading].</p>
<ol start="6">
<li><strong>Registration&nbsp;and&nbsp;accounts</strong></li>
</ol>
<p>6.1[To&nbsp;be&nbsp;eligible&nbsp;for&nbsp;an&nbsp;individual&nbsp;account&nbsp;on&nbsp;our&nbsp;website&nbsp;under&nbsp;this&nbsp;Section&nbsp;6,&nbsp;you&nbsp;must&nbsp;[be&nbsp;at&nbsp;least&nbsp;18&nbsp;years&nbsp;of&nbsp;age&nbsp;and&nbsp;resident&nbsp;in&nbsp;the&nbsp;United&nbsp;Kingdom].]</p>
<p>6.2You&nbsp;may&nbsp;register&nbsp;for&nbsp;an&nbsp;account&nbsp;with&nbsp;our&nbsp;website&nbsp;by&nbsp;[completing&nbsp;and&nbsp;submitting&nbsp;the&nbsp;account&nbsp;registration&nbsp;form&nbsp;on&nbsp;our&nbsp;website,&nbsp;and&nbsp;clicking&nbsp;on&nbsp;the&nbsp;verification&nbsp;link&nbsp;in&nbsp;the&nbsp;email&nbsp;that&nbsp;the&nbsp;website&nbsp;will&nbsp;send&nbsp;to&nbsp;you].</p>
<p>6.3You&nbsp;must&nbsp;notify&nbsp;us&nbsp;in&nbsp;writing&nbsp;immediately&nbsp;if&nbsp;you&nbsp;become&nbsp;aware&nbsp;of&nbsp;any&nbsp;unauthorised&nbsp;use&nbsp;of&nbsp;your&nbsp;account.</p>
<p>6.4You&nbsp;must&nbsp;not&nbsp;use&nbsp;any&nbsp;other&nbsp;person's&nbsp;account&nbsp;to&nbsp;access&nbsp;the&nbsp;website[,&nbsp;unless&nbsp;you&nbsp;have&nbsp;that&nbsp;person's&nbsp;express&nbsp;permission&nbsp;to&nbsp;do&nbsp;so].</p>
<ol start="7">
<li><strong>User&nbsp;IDs&nbsp;and&nbsp;passwords</strong></li>
</ol>
<p>7.1If&nbsp;you&nbsp;register&nbsp;for&nbsp;an&nbsp;account&nbsp;with&nbsp;our&nbsp;website,&nbsp;[we&nbsp;will&nbsp;provide&nbsp;you&nbsp;with&nbsp;/&nbsp;you&nbsp;will&nbsp;be&nbsp;asked&nbsp;to&nbsp;choose]&nbsp;a&nbsp;user&nbsp;ID&nbsp;and&nbsp;password.</p>
<p>7.2Your&nbsp;user&nbsp;ID&nbsp;must&nbsp;not&nbsp;be&nbsp;liable&nbsp;to&nbsp;mislead&nbsp;and&nbsp;must&nbsp;comply&nbsp;with&nbsp;the&nbsp;content&nbsp;rules&nbsp;set&nbsp;out&nbsp;in&nbsp;Section&nbsp;10;&nbsp;you&nbsp;must&nbsp;not&nbsp;use&nbsp;your&nbsp;account&nbsp;or&nbsp;user&nbsp;ID&nbsp;for&nbsp;or&nbsp;in&nbsp;connection&nbsp;with&nbsp;the&nbsp;impersonation&nbsp;of&nbsp;any&nbsp;person.&nbsp;</p>
<p>7.3You&nbsp;must&nbsp;keep&nbsp;your&nbsp;password&nbsp;confidential.</p>
<p>7.4You&nbsp;must&nbsp;notify&nbsp;us&nbsp;in&nbsp;writing&nbsp;immediately&nbsp;if&nbsp;you&nbsp;become&nbsp;aware&nbsp;of&nbsp;any&nbsp;disclosure&nbsp;of&nbsp;your&nbsp;password.</p>
<p>7.5You&nbsp;are&nbsp;responsible&nbsp;for&nbsp;any&nbsp;activity&nbsp;on&nbsp;our&nbsp;website&nbsp;arising&nbsp;out&nbsp;of&nbsp;any&nbsp;failure&nbsp;to&nbsp;keep&nbsp;your&nbsp;password&nbsp;confidential,&nbsp;and&nbsp;may&nbsp;be&nbsp;held&nbsp;liable&nbsp;for&nbsp;any&nbsp;losses&nbsp;arising&nbsp;out&nbsp;of&nbsp;such&nbsp;a&nbsp;failure.</p>
<ol start="8">
<li><strong>Cancellation&nbsp;and&nbsp;suspension&nbsp;of&nbsp;account</strong></li>
</ol>
<p>8.1We&nbsp;may:</p>
<p>(a)[suspend&nbsp;your&nbsp;account;]</p>
<p>(b)[cancel&nbsp;your&nbsp;account;&nbsp;and/or]</p>
<p>(c)[edit&nbsp;your&nbsp;account&nbsp;details,]</p>
<p>at&nbsp;any&nbsp;time&nbsp;in&nbsp;our&nbsp;sole&nbsp;discretion&nbsp;without&nbsp;notice&nbsp;or&nbsp;explanation.</p>
<p>8.2You&nbsp;may&nbsp;cancel&nbsp;your&nbsp;account&nbsp;on&nbsp;our&nbsp;website&nbsp;[using&nbsp;your&nbsp;account&nbsp;control&nbsp;panel&nbsp;on&nbsp;the&nbsp;website].</p>
<ol start="9">
<li><strong>Your&nbsp;content:&nbsp;licence</strong></li>
</ol>
<p>9.1In&nbsp;these&nbsp;terms&nbsp;and&nbsp;conditions,&nbsp;"your&nbsp;content"&nbsp;means&nbsp;all&nbsp;works&nbsp;and&nbsp;materials&nbsp;(including&nbsp;without&nbsp;limitation&nbsp;text,&nbsp;graphics,&nbsp;images,&nbsp;audio&nbsp;material,&nbsp;video&nbsp;material,&nbsp;audio-visual&nbsp;material,&nbsp;scripts,&nbsp;software&nbsp;and&nbsp;files)&nbsp;that&nbsp;you&nbsp;submit&nbsp;to&nbsp;us&nbsp;or&nbsp;our&nbsp;website&nbsp;for&nbsp;storage&nbsp;or&nbsp;publication&nbsp;on,&nbsp;processing&nbsp;by,&nbsp;or&nbsp;transmission&nbsp;via,&nbsp;our&nbsp;website.</p>
<p>9.2You&nbsp;grant&nbsp;to&nbsp;us&nbsp;a&nbsp;[worldwide,&nbsp;irrevocable,&nbsp;non-exclusive,&nbsp;royalty-free&nbsp;licence]&nbsp;to&nbsp;[use,&nbsp;reproduce,&nbsp;store,&nbsp;adapt,&nbsp;publish,&nbsp;translate&nbsp;and&nbsp;distribute&nbsp;your&nbsp;content&nbsp;in&nbsp;any&nbsp;existing&nbsp;or&nbsp;future&nbsp;media&nbsp;/&nbsp;reproduce,&nbsp;store&nbsp;and&nbsp;publish&nbsp;your&nbsp;content&nbsp;on&nbsp;and&nbsp;in&nbsp;relation&nbsp;to&nbsp;this&nbsp;website&nbsp;and&nbsp;any&nbsp;successor&nbsp;website&nbsp;/&nbsp;reproduce,&nbsp;store&nbsp;and,&nbsp;with&nbsp;your&nbsp;specific&nbsp;consent,&nbsp;publish&nbsp;your&nbsp;content&nbsp;on&nbsp;and&nbsp;in&nbsp;relation&nbsp;to&nbsp;this&nbsp;website].</p>
<p>9.3You&nbsp;grant&nbsp;to&nbsp;us&nbsp;the&nbsp;right&nbsp;to&nbsp;sub-license&nbsp;the&nbsp;rights&nbsp;licensed&nbsp;under&nbsp;Section&nbsp;9.2.</p>
<p>9.4[You&nbsp;grant&nbsp;to&nbsp;us&nbsp;the&nbsp;right&nbsp;to&nbsp;bring&nbsp;an&nbsp;action&nbsp;for&nbsp;infringement&nbsp;of&nbsp;the&nbsp;rights&nbsp;licensed&nbsp;under&nbsp;Section&nbsp;9.2.]</p>
<p>9.5[You&nbsp;hereby&nbsp;waive&nbsp;all&nbsp;your&nbsp;moral&nbsp;rights&nbsp;in&nbsp;your&nbsp;content&nbsp;to&nbsp;the&nbsp;maximum&nbsp;extent&nbsp;permitted&nbsp;by&nbsp;applicable&nbsp;law;&nbsp;and&nbsp;you&nbsp;warrant&nbsp;and&nbsp;represent&nbsp;that&nbsp;all&nbsp;other&nbsp;moral&nbsp;rights&nbsp;in&nbsp;your&nbsp;content&nbsp;have&nbsp;been&nbsp;waived&nbsp;to&nbsp;the&nbsp;maximum&nbsp;extent&nbsp;permitted&nbsp;by&nbsp;applicable&nbsp;law.]</p>
<p>9.6[You&nbsp;may&nbsp;edit&nbsp;your&nbsp;content&nbsp;to&nbsp;the&nbsp;extent&nbsp;permitted&nbsp;using&nbsp;the&nbsp;editing&nbsp;functionality&nbsp;made&nbsp;available&nbsp;on&nbsp;our&nbsp;website.]</p>
<p>9.7Without&nbsp;prejudice&nbsp;to&nbsp;our&nbsp;other&nbsp;rights&nbsp;under&nbsp;these&nbsp;terms&nbsp;and&nbsp;conditions,&nbsp;if&nbsp;you&nbsp;breach&nbsp;any&nbsp;provision&nbsp;of&nbsp;these&nbsp;terms&nbsp;and&nbsp;conditions&nbsp;in&nbsp;any&nbsp;way,&nbsp;or&nbsp;if&nbsp;we&nbsp;reasonably&nbsp;suspect&nbsp;that&nbsp;you&nbsp;have&nbsp;breached&nbsp;these&nbsp;terms&nbsp;and&nbsp;conditions&nbsp;in&nbsp;any&nbsp;way,&nbsp;we&nbsp;may&nbsp;delete,&nbsp;unpublish&nbsp;or&nbsp;edit&nbsp;any&nbsp;or&nbsp;all&nbsp;of&nbsp;your&nbsp;content.</p>
<ol>
<li><strong>Your&nbsp;content:&nbsp;rules</strong></li>
</ol>
<p>10.1You&nbsp;warrant&nbsp;and&nbsp;represent&nbsp;that&nbsp;your&nbsp;content&nbsp;will&nbsp;comply&nbsp;with&nbsp;these&nbsp;terms&nbsp;and&nbsp;conditions.</p>
<p>10.2Your&nbsp;content&nbsp;must&nbsp;not&nbsp;be&nbsp;illegal&nbsp;or&nbsp;unlawful,&nbsp;must&nbsp;not&nbsp;infringe&nbsp;any&nbsp;person's&nbsp;legal&nbsp;rights,&nbsp;and&nbsp;must&nbsp;not&nbsp;be&nbsp;capable&nbsp;of&nbsp;giving&nbsp;rise&nbsp;to&nbsp;legal&nbsp;action&nbsp;against&nbsp;any&nbsp;person&nbsp;(in&nbsp;each&nbsp;case&nbsp;in&nbsp;any&nbsp;jurisdiction&nbsp;and&nbsp;under&nbsp;any&nbsp;applicable&nbsp;law).</p>
<p>10.3Your&nbsp;content,&nbsp;and&nbsp;the&nbsp;use&nbsp;of&nbsp;your&nbsp;content&nbsp;by&nbsp;us&nbsp;in&nbsp;accordance&nbsp;with&nbsp;these&nbsp;terms&nbsp;and&nbsp;conditions,&nbsp;must&nbsp;not:</p>
<p>(a)be&nbsp;libellous&nbsp;or&nbsp;maliciously&nbsp;false;</p>
<p>(b)be&nbsp;obscene&nbsp;or&nbsp;indecent;</p>
<p>(c)infringe&nbsp;any&nbsp;copyright,&nbsp;moral&nbsp;right,&nbsp;database&nbsp;right,&nbsp;trade&nbsp;mark&nbsp;right,&nbsp;design&nbsp;right,&nbsp;right&nbsp;in&nbsp;passing&nbsp;off,&nbsp;or&nbsp;other&nbsp;intellectual&nbsp;property&nbsp;right;</p>
<p>(d)infringe&nbsp;any&nbsp;right&nbsp;of&nbsp;confidence,&nbsp;right&nbsp;of&nbsp;privacy&nbsp;or&nbsp;right&nbsp;under&nbsp;data&nbsp;protection&nbsp;legislation;</p>
<p>(e)constitute&nbsp;negligent&nbsp;advice&nbsp;or&nbsp;contain&nbsp;any&nbsp;negligent&nbsp;statement;</p>
<p>(f)constitute&nbsp;an&nbsp;incitement&nbsp;to&nbsp;commit&nbsp;a&nbsp;crime[,&nbsp;instructions&nbsp;for&nbsp;the&nbsp;commission&nbsp;of&nbsp;a&nbsp;crime&nbsp;or&nbsp;the&nbsp;promotion&nbsp;of&nbsp;criminal&nbsp;activity];</p>
<p>(g)be&nbsp;in&nbsp;contempt&nbsp;of&nbsp;any&nbsp;court,&nbsp;or&nbsp;in&nbsp;breach&nbsp;of&nbsp;any&nbsp;court&nbsp;order;</p>
<p>(h)be&nbsp;in&nbsp;breach&nbsp;of&nbsp;racial&nbsp;or&nbsp;religious&nbsp;hatred&nbsp;or&nbsp;discrimination&nbsp;legislation;</p>
<p>(i)be&nbsp;blasphemous;</p>
<p>(j)be&nbsp;in&nbsp;breach&nbsp;of&nbsp;official&nbsp;secrets&nbsp;legislation;</p>
<p>(k)be&nbsp;in&nbsp;breach&nbsp;of&nbsp;any&nbsp;contractual&nbsp;obligation&nbsp;owed&nbsp;to&nbsp;any&nbsp;person;</p>
<p>(l)[depict&nbsp;violence[,&nbsp;in&nbsp;an&nbsp;explicit,&nbsp;graphic&nbsp;or&nbsp;gratuitous&nbsp;manner];]</p>
<p>(m)[be&nbsp;pornographic[,&nbsp;lewd,&nbsp;suggestive&nbsp;or&nbsp;sexually&nbsp;explicit];]</p>
<p>(n)[be&nbsp;untrue,&nbsp;false,&nbsp;inaccurate&nbsp;or&nbsp;misleading;]</p>
<p>(o)[consist&nbsp;of&nbsp;or&nbsp;contain&nbsp;any&nbsp;instructions,&nbsp;advice&nbsp;or&nbsp;other&nbsp;information&nbsp;which&nbsp;may&nbsp;be&nbsp;acted&nbsp;upon&nbsp;and&nbsp;could,&nbsp;if&nbsp;acted&nbsp;upon,&nbsp;cause&nbsp;illness,&nbsp;injury&nbsp;or&nbsp;death,&nbsp;or&nbsp;any&nbsp;other&nbsp;loss&nbsp;or&nbsp;damage;]</p>
<p>(p)[constitute&nbsp;spam;]</p>
<p>(q)[be&nbsp;offensive,&nbsp;deceptive,&nbsp;fraudulent,&nbsp;threatening,&nbsp;abusive,&nbsp;harassing,&nbsp;anti-social,&nbsp;menacing,&nbsp;hateful,&nbsp;discriminatory&nbsp;or&nbsp;inflammatory;&nbsp;or]</p>
<p>(r)[cause&nbsp;annoyance,&nbsp;inconvenience&nbsp;or&nbsp;needless&nbsp;anxiety&nbsp;to&nbsp;any&nbsp;person.]</p>
<ol>
<li><strong>Limited&nbsp;warranties</strong></li>
</ol>
<p>11.1We&nbsp;do&nbsp;not&nbsp;warrant&nbsp;or&nbsp;represent:</p>
<p>(a)the&nbsp;completeness&nbsp;or&nbsp;accuracy&nbsp;of&nbsp;the&nbsp;information&nbsp;published&nbsp;on&nbsp;our&nbsp;website;</p>
<p>(b)that&nbsp;the&nbsp;material&nbsp;on&nbsp;the&nbsp;website&nbsp;is&nbsp;up&nbsp;to&nbsp;date;&nbsp;or</p>
<p>(c)that&nbsp;the&nbsp;website&nbsp;or&nbsp;any&nbsp;service&nbsp;on&nbsp;the&nbsp;website&nbsp;will&nbsp;remain&nbsp;available.</p>
<p>11.2We&nbsp;reserve&nbsp;the&nbsp;right&nbsp;to&nbsp;discontinue&nbsp;or&nbsp;alter&nbsp;any&nbsp;or&nbsp;all&nbsp;of&nbsp;our&nbsp;website&nbsp;services,&nbsp;and&nbsp;to&nbsp;stop&nbsp;publishing&nbsp;our&nbsp;website,&nbsp;at&nbsp;any&nbsp;time&nbsp;in&nbsp;our&nbsp;sole&nbsp;discretion&nbsp;without&nbsp;notice&nbsp;or&nbsp;explanation;&nbsp;and&nbsp;save&nbsp;to&nbsp;the&nbsp;extent&nbsp;expressly&nbsp;provided&nbsp;otherwise&nbsp;in&nbsp;these&nbsp;terms&nbsp;and&nbsp;conditions,&nbsp;you&nbsp;will&nbsp;not&nbsp;be&nbsp;entitled&nbsp;to&nbsp;any&nbsp;compensation&nbsp;or&nbsp;other&nbsp;payment&nbsp;upon&nbsp;the&nbsp;discontinuance&nbsp;or&nbsp;alteration&nbsp;of&nbsp;any&nbsp;website&nbsp;services,&nbsp;or&nbsp;if&nbsp;we&nbsp;stop&nbsp;publishing&nbsp;the&nbsp;website.</p>
<p>11.3To&nbsp;the&nbsp;maximum&nbsp;extent&nbsp;permitted&nbsp;by&nbsp;applicable&nbsp;law&nbsp;and&nbsp;subject&nbsp;to&nbsp;Section&nbsp;12.1,&nbsp;we&nbsp;exclude&nbsp;all&nbsp;representations&nbsp;and&nbsp;warranties&nbsp;relating&nbsp;to&nbsp;the&nbsp;subject&nbsp;matter&nbsp;of&nbsp;these&nbsp;terms&nbsp;and&nbsp;conditions,&nbsp;our&nbsp;website&nbsp;and&nbsp;the&nbsp;use&nbsp;of&nbsp;our&nbsp;website.</p>
<ol start="2">
<li><strong>Limitations&nbsp;and&nbsp;exclusions&nbsp;of&nbsp;liability</strong></li>
</ol>
<p>12.1Nothing&nbsp;in&nbsp;these&nbsp;terms&nbsp;and&nbsp;conditions&nbsp;will:</p>
<p>(a)limit&nbsp;or&nbsp;exclude&nbsp;any&nbsp;liability&nbsp;for&nbsp;death&nbsp;or&nbsp;personal&nbsp;injury&nbsp;resulting&nbsp;from&nbsp;negligence;</p>
<p>(b)limit&nbsp;or&nbsp;exclude&nbsp;any&nbsp;liability&nbsp;for&nbsp;fraud&nbsp;or&nbsp;fraudulent&nbsp;misrepresentation;</p>
<p>(c)limit&nbsp;any&nbsp;liabilities&nbsp;in&nbsp;any&nbsp;way&nbsp;that&nbsp;is&nbsp;not&nbsp;permitted&nbsp;under&nbsp;applicable&nbsp;law;&nbsp;or</p>
<p>(d)exclude&nbsp;any&nbsp;liabilities&nbsp;that&nbsp;may&nbsp;not&nbsp;be&nbsp;excluded&nbsp;under&nbsp;applicable&nbsp;law.</p>
<p>12.2The&nbsp;limitations&nbsp;and&nbsp;exclusions&nbsp;of&nbsp;liability&nbsp;set&nbsp;out&nbsp;in&nbsp;this&nbsp;Section&nbsp;12&nbsp;and&nbsp;elsewhere&nbsp;in&nbsp;these&nbsp;terms&nbsp;and&nbsp;conditions:&nbsp;</p>
<p>(a)are&nbsp;subject&nbsp;to&nbsp;Section&nbsp;12.1;&nbsp;and</p>
<p>(b)govern&nbsp;all&nbsp;liabilities&nbsp;arising&nbsp;under&nbsp;these&nbsp;terms&nbsp;and&nbsp;conditions&nbsp;or&nbsp;relating&nbsp;to&nbsp;the&nbsp;subject&nbsp;matter&nbsp;of&nbsp;these&nbsp;terms&nbsp;and&nbsp;conditions,&nbsp;including&nbsp;liabilities&nbsp;arising&nbsp;in&nbsp;contract,&nbsp;in&nbsp;tort&nbsp;(including&nbsp;negligence)&nbsp;and&nbsp;for&nbsp;breach&nbsp;of&nbsp;statutory&nbsp;duty.</p>
<p>12.3[To&nbsp;the&nbsp;extent&nbsp;that&nbsp;our&nbsp;website&nbsp;and&nbsp;the&nbsp;information&nbsp;and&nbsp;services&nbsp;on&nbsp;our&nbsp;website&nbsp;are&nbsp;provided&nbsp;free&nbsp;of&nbsp;charge,&nbsp;we&nbsp;will&nbsp;not&nbsp;be&nbsp;liable&nbsp;for&nbsp;any&nbsp;loss&nbsp;or&nbsp;damage&nbsp;of&nbsp;any&nbsp;nature.]</p>
<p>12.4We&nbsp;will&nbsp;not&nbsp;be&nbsp;liable&nbsp;to&nbsp;you&nbsp;in&nbsp;respect&nbsp;of&nbsp;any&nbsp;losses&nbsp;arising&nbsp;out&nbsp;of&nbsp;any&nbsp;event&nbsp;or&nbsp;events&nbsp;beyond&nbsp;our&nbsp;reasonable&nbsp;control.</p>
<p>12.5We&nbsp;will&nbsp;not&nbsp;be&nbsp;liable&nbsp;to&nbsp;you&nbsp;in&nbsp;respect&nbsp;of&nbsp;any&nbsp;business&nbsp;losses,&nbsp;including&nbsp;(without&nbsp;limitation)&nbsp;loss&nbsp;of&nbsp;or&nbsp;damage&nbsp;to&nbsp;profits,&nbsp;income,&nbsp;revenue,&nbsp;use,&nbsp;production,&nbsp;anticipated&nbsp;savings,&nbsp;business,&nbsp;contracts,&nbsp;commercial&nbsp;opportunities&nbsp;or&nbsp;goodwill.</p>
<p>12.6We&nbsp;will&nbsp;not&nbsp;be&nbsp;liable&nbsp;to&nbsp;you&nbsp;in&nbsp;respect&nbsp;of&nbsp;any&nbsp;loss&nbsp;or&nbsp;corruption&nbsp;of&nbsp;any&nbsp;data,&nbsp;database&nbsp;or&nbsp;software.</p>
<p>12.7We&nbsp;will&nbsp;not&nbsp;be&nbsp;liable&nbsp;to&nbsp;you&nbsp;in&nbsp;respect&nbsp;of&nbsp;any&nbsp;special,&nbsp;indirect&nbsp;or&nbsp;consequential&nbsp;loss&nbsp;or&nbsp;damage.</p>
<p>12.8[You&nbsp;accept&nbsp;that&nbsp;we&nbsp;have&nbsp;an&nbsp;interest&nbsp;in&nbsp;limiting&nbsp;the&nbsp;personal&nbsp;liability&nbsp;of&nbsp;our&nbsp;officers&nbsp;and&nbsp;employees&nbsp;and,&nbsp;having&nbsp;regard&nbsp;to&nbsp;that&nbsp;interest,&nbsp;you&nbsp;acknowledge&nbsp;that&nbsp;we&nbsp;are&nbsp;a&nbsp;limited&nbsp;liability&nbsp;entity;&nbsp;you&nbsp;agree&nbsp;that&nbsp;you&nbsp;will&nbsp;not&nbsp;bring&nbsp;any&nbsp;claim&nbsp;personally&nbsp;against&nbsp;our&nbsp;officers&nbsp;or&nbsp;employees&nbsp;in&nbsp;respect&nbsp;of&nbsp;any&nbsp;losses&nbsp;you&nbsp;suffer&nbsp;in&nbsp;connection&nbsp;with&nbsp;the&nbsp;website&nbsp;or&nbsp;these&nbsp;terms&nbsp;and&nbsp;conditions&nbsp;(this&nbsp;will&nbsp;not,&nbsp;of&nbsp;course,&nbsp;limit&nbsp;or&nbsp;exclude&nbsp;the&nbsp;liability&nbsp;of&nbsp;the&nbsp;limited&nbsp;liability&nbsp;entity&nbsp;itself&nbsp;for&nbsp;the&nbsp;acts&nbsp;and&nbsp;omissions&nbsp;of&nbsp;our&nbsp;officers&nbsp;and&nbsp;employees).]</p>
<ol start="3">
<li><strong>Breaches&nbsp;of&nbsp;these&nbsp;terms&nbsp;and&nbsp;conditions</strong></li>
</ol>
<p>13.1Without&nbsp;prejudice&nbsp;to&nbsp;our&nbsp;other&nbsp;rights&nbsp;under&nbsp;these&nbsp;terms&nbsp;and&nbsp;conditions,&nbsp;if&nbsp;you&nbsp;breach&nbsp;these&nbsp;terms&nbsp;and&nbsp;conditions&nbsp;in&nbsp;any&nbsp;way,&nbsp;or&nbsp;if&nbsp;we&nbsp;reasonably&nbsp;suspect&nbsp;that&nbsp;you&nbsp;have&nbsp;breached&nbsp;these&nbsp;terms&nbsp;and&nbsp;conditions&nbsp;in&nbsp;any&nbsp;way,&nbsp;we&nbsp;may:&nbsp;</p>
<p>(a)send&nbsp;you&nbsp;one&nbsp;or&nbsp;more&nbsp;formal&nbsp;warnings;</p>
<p>(b)temporarily&nbsp;suspend&nbsp;your&nbsp;access&nbsp;to&nbsp;our&nbsp;website;</p>
<p>(c)permanently&nbsp;prohibit&nbsp;you&nbsp;from&nbsp;accessing&nbsp;our&nbsp;website;</p>
<p>(d)block&nbsp;computers&nbsp;using&nbsp;your&nbsp;IP&nbsp;address&nbsp;from&nbsp;accessing&nbsp;our&nbsp;website;</p>
<p>(e)contact&nbsp;any&nbsp;or&nbsp;all&nbsp;your&nbsp;internet&nbsp;service&nbsp;providers&nbsp;and&nbsp;request&nbsp;that&nbsp;they&nbsp;block&nbsp;your&nbsp;access&nbsp;to&nbsp;our&nbsp;website;</p>
<p>(f)commence&nbsp;legal&nbsp;action&nbsp;against&nbsp;you,&nbsp;whether&nbsp;for&nbsp;breach&nbsp;of&nbsp;contract&nbsp;or&nbsp;otherwise;&nbsp;and/or</p>
<p>(g)suspend&nbsp;or&nbsp;delete&nbsp;your&nbsp;account&nbsp;on&nbsp;our&nbsp;website.</p>
<p>13.2Where&nbsp;we&nbsp;suspend&nbsp;or&nbsp;prohibit&nbsp;or&nbsp;block&nbsp;your&nbsp;access&nbsp;to&nbsp;our&nbsp;website&nbsp;or&nbsp;a&nbsp;part&nbsp;of&nbsp;our&nbsp;website,&nbsp;you&nbsp;must&nbsp;not&nbsp;take&nbsp;any&nbsp;action&nbsp;to&nbsp;circumvent&nbsp;such&nbsp;suspension&nbsp;or&nbsp;prohibition&nbsp;or&nbsp;blocking&nbsp;(including&nbsp;without&nbsp;limitation&nbsp;creating&nbsp;and/or&nbsp;using&nbsp;a&nbsp;different&nbsp;account).</p>
<ol start="4">
<li><strong>Variation</strong></li>
</ol>
<p>14.1We&nbsp;may&nbsp;revise&nbsp;these&nbsp;terms&nbsp;and&nbsp;conditions&nbsp;from&nbsp;time&nbsp;to&nbsp;time.</p>
<p>14.2[The&nbsp;revised&nbsp;terms&nbsp;and&nbsp;conditions&nbsp;shall&nbsp;apply&nbsp;to&nbsp;the&nbsp;use&nbsp;of&nbsp;our&nbsp;website&nbsp;from&nbsp;the&nbsp;date&nbsp;of&nbsp;publication&nbsp;of&nbsp;the&nbsp;revised&nbsp;terms&nbsp;and&nbsp;conditions&nbsp;on&nbsp;the&nbsp;website,&nbsp;and&nbsp;you&nbsp;hereby&nbsp;waive&nbsp;any&nbsp;right&nbsp;you&nbsp;may&nbsp;otherwise&nbsp;have&nbsp;to&nbsp;be&nbsp;notified&nbsp;of,&nbsp;or&nbsp;to&nbsp;consent&nbsp;to,&nbsp;revisions&nbsp;of&nbsp;these&nbsp;terms&nbsp;and&nbsp;conditions.&nbsp;/&nbsp;We&nbsp;will&nbsp;give&nbsp;you&nbsp;written&nbsp;notice&nbsp;of&nbsp;any&nbsp;revision&nbsp;of&nbsp;these&nbsp;terms&nbsp;and&nbsp;conditions,&nbsp;and&nbsp;the&nbsp;revised&nbsp;terms&nbsp;and&nbsp;conditions&nbsp;will&nbsp;apply&nbsp;to&nbsp;the&nbsp;use&nbsp;of&nbsp;our&nbsp;website&nbsp;from&nbsp;the&nbsp;date&nbsp;that&nbsp;we&nbsp;give&nbsp;you&nbsp;such&nbsp;notice;&nbsp;if&nbsp;you&nbsp;do&nbsp;not&nbsp;agree&nbsp;to&nbsp;the&nbsp;revised&nbsp;terms&nbsp;and&nbsp;conditions,&nbsp;you&nbsp;must&nbsp;stop&nbsp;using&nbsp;our&nbsp;website.]</p>
<p>14.3[If&nbsp;you&nbsp;have&nbsp;given&nbsp;your&nbsp;express&nbsp;agreement&nbsp;to&nbsp;these&nbsp;terms&nbsp;and&nbsp;conditions,&nbsp;we&nbsp;will&nbsp;ask&nbsp;for&nbsp;your&nbsp;express&nbsp;agreement&nbsp;to&nbsp;any&nbsp;revision&nbsp;of&nbsp;these&nbsp;terms&nbsp;and&nbsp;conditions;&nbsp;and&nbsp;if&nbsp;you&nbsp;do&nbsp;not&nbsp;give&nbsp;your&nbsp;express&nbsp;agreement&nbsp;to&nbsp;the&nbsp;revised&nbsp;terms&nbsp;and&nbsp;conditions&nbsp;within&nbsp;such&nbsp;period&nbsp;as&nbsp;we&nbsp;may&nbsp;specify,&nbsp;we&nbsp;will&nbsp;disable&nbsp;or&nbsp;delete&nbsp;your&nbsp;account&nbsp;on&nbsp;the&nbsp;website,&nbsp;and&nbsp;you&nbsp;must&nbsp;stop&nbsp;using&nbsp;the&nbsp;website.]</p>
<ol start="5">
<li><strong>Assignment</strong></li>
</ol>
<p>15.1You&nbsp;hereby&nbsp;agree&nbsp;that&nbsp;we&nbsp;may&nbsp;assign,&nbsp;transfer,&nbsp;sub-contract&nbsp;or&nbsp;otherwise&nbsp;deal&nbsp;with&nbsp;our&nbsp;rights&nbsp;and/or&nbsp;obligations&nbsp;under&nbsp;these&nbsp;terms&nbsp;and&nbsp;conditions.&nbsp;</p>
<p>15.2You&nbsp;may&nbsp;not&nbsp;without&nbsp;our&nbsp;prior&nbsp;written&nbsp;consent&nbsp;assign,&nbsp;transfer,&nbsp;sub-contract&nbsp;or&nbsp;otherwise&nbsp;deal&nbsp;with&nbsp;any&nbsp;of&nbsp;your&nbsp;rights&nbsp;and/or&nbsp;obligations&nbsp;under&nbsp;these&nbsp;terms&nbsp;and&nbsp;conditions.&nbsp;</p>
<ol start="6">
<li><strong>Severability</strong></li>
</ol>
<p>16.1If&nbsp;a&nbsp;provision&nbsp;of&nbsp;these&nbsp;terms&nbsp;and&nbsp;conditions&nbsp;is&nbsp;determined&nbsp;by&nbsp;any&nbsp;court&nbsp;or&nbsp;other&nbsp;competent&nbsp;authority&nbsp;to&nbsp;be&nbsp;unlawful&nbsp;and/or&nbsp;unenforceable,&nbsp;the&nbsp;other&nbsp;provisions&nbsp;will&nbsp;continue&nbsp;in&nbsp;effect.</p>
<p>16.2If&nbsp;any&nbsp;unlawful&nbsp;and/or&nbsp;unenforceable&nbsp;provision&nbsp;of&nbsp;these&nbsp;terms&nbsp;and&nbsp;conditions&nbsp;would&nbsp;be&nbsp;lawful&nbsp;or&nbsp;enforceable&nbsp;if&nbsp;part&nbsp;of&nbsp;it&nbsp;were&nbsp;deleted,&nbsp;that&nbsp;part&nbsp;will&nbsp;be&nbsp;deemed&nbsp;to&nbsp;be&nbsp;deleted,&nbsp;and&nbsp;the&nbsp;rest&nbsp;of&nbsp;the&nbsp;provision&nbsp;will&nbsp;continue&nbsp;in&nbsp;effect.&nbsp;</p>
<ol start="7">
<li><strong>Third&nbsp;party&nbsp;rights</strong></li>
</ol>
<p>17.1These&nbsp;terms&nbsp;and&nbsp;conditions&nbsp;are&nbsp;for&nbsp;our&nbsp;benefit&nbsp;and&nbsp;your&nbsp;benefit,&nbsp;and&nbsp;these&nbsp;terms&nbsp;and&nbsp;conditions&nbsp;are&nbsp;not&nbsp;intended&nbsp;to&nbsp;benefit&nbsp;or&nbsp;be&nbsp;enforceable&nbsp;by&nbsp;any&nbsp;third&nbsp;party.</p>
<p>17.2The&nbsp;exercise&nbsp;of&nbsp;the&nbsp;parties'&nbsp;rights&nbsp;under&nbsp;these&nbsp;terms&nbsp;and&nbsp;conditions&nbsp;is&nbsp;not&nbsp;subject&nbsp;to&nbsp;the&nbsp;consent&nbsp;of&nbsp;any&nbsp;third&nbsp;party.</p>
<ol start="8">
<li><strong>Entire&nbsp;agreement</strong></li>
</ol>
<p>18.1Subject&nbsp;to&nbsp;Section&nbsp;12.1,&nbsp;these&nbsp;terms&nbsp;and&nbsp;conditions,&nbsp;together&nbsp;with&nbsp;[our&nbsp;privacy&nbsp;and&nbsp;cookies&nbsp;policy],&nbsp;shall&nbsp;constitute&nbsp;the&nbsp;entire&nbsp;agreement&nbsp;between&nbsp;you&nbsp;and&nbsp;us&nbsp;in&nbsp;relation&nbsp;to&nbsp;your&nbsp;use&nbsp;of&nbsp;our&nbsp;website&nbsp;and&nbsp;shall&nbsp;supersede&nbsp;all&nbsp;previous&nbsp;agreements&nbsp;between&nbsp;you&nbsp;and&nbsp;us&nbsp;in&nbsp;relation&nbsp;to&nbsp;your&nbsp;use&nbsp;of&nbsp;our&nbsp;website.</p>
<ol start="9">
<li><strong>Law&nbsp;and&nbsp;jurisdiction</strong></li>
</ol>
<p>19.1These&nbsp;terms&nbsp;and&nbsp;conditions&nbsp;shall&nbsp;be&nbsp;governed&nbsp;by&nbsp;and&nbsp;construed&nbsp;in&nbsp;accordance&nbsp;with&nbsp;[English&nbsp;law].</p>
<p>19.2Any&nbsp;disputes&nbsp;relating&nbsp;to&nbsp;these&nbsp;terms&nbsp;and&nbsp;conditions&nbsp;shall&nbsp;be&nbsp;subject&nbsp;to&nbsp;the&nbsp;[exclusive&nbsp;/&nbsp;non-exclusive]&nbsp;jurisdiction&nbsp;of&nbsp;the&nbsp;courts&nbsp;of&nbsp;[England].</p>
<ol>
<li><strong>Statutory&nbsp;and&nbsp;regulatory&nbsp;disclosures</strong></li>
</ol>
<p>20.1[We&nbsp;are&nbsp;registered&nbsp;in&nbsp;[<em>trade&nbsp;register</em>];&nbsp;you&nbsp;can&nbsp;find&nbsp;the&nbsp;online&nbsp;version&nbsp;of&nbsp;the&nbsp;register&nbsp;at&nbsp;[<em>URL</em>],&nbsp;and&nbsp;our&nbsp;registration&nbsp;number&nbsp;is&nbsp;[<em>number</em>].]</p>
<p>20.2[We&nbsp;are&nbsp;subject&nbsp;to&nbsp;[<em>authorisation&nbsp;scheme</em>],&nbsp;which&nbsp;is&nbsp;supervised&nbsp;by&nbsp;[<em>supervisory&nbsp;authority</em>].]</p>
<p>20.3[We&nbsp;are&nbsp;registered&nbsp;as&nbsp;[<em>title</em>]&nbsp;with&nbsp;[<em>professional&nbsp;body</em>]&nbsp;in&nbsp;[<em>the&nbsp;United&nbsp;Kingdom</em>]&nbsp;and&nbsp;are&nbsp;subject&nbsp;to&nbsp;[<em>rules</em>],&nbsp;which&nbsp;can&nbsp;be&nbsp;found&nbsp;at&nbsp;[<em>URL</em>].]</p>
<p>20.4[We&nbsp;subscribe&nbsp;to&nbsp;[<em>code(s)&nbsp;of&nbsp;conduct</em>],&nbsp;which&nbsp;can&nbsp;be&nbsp;consulted&nbsp;electronically&nbsp;at&nbsp;[<em>URL(s)</em>].]</p>
<p>20.5[Our&nbsp;VAT&nbsp;number&nbsp;is&nbsp;[<em>number</em>].]</p>
<ol>
<li><strong>Our&nbsp;details</strong></li>
</ol>
<p>21.1This&nbsp;website&nbsp;is&nbsp;owned&nbsp;and&nbsp;operated&nbsp;by&nbsp;[<em>name</em>].</p>
<p>21.2[We&nbsp;are&nbsp;registered&nbsp;in&nbsp;[England&nbsp;and&nbsp;Wales]&nbsp;under&nbsp;registration&nbsp;number&nbsp;[<em>number</em>],&nbsp;and&nbsp;our&nbsp;registered&nbsp;office&nbsp;is&nbsp;at&nbsp;[<em>address</em>].]</p>
<p>21.3Our&nbsp;principal&nbsp;place&nbsp;of&nbsp;business&nbsp;is&nbsp;at&nbsp;[<em>address</em>].</p>
<p>21.4You&nbsp;can&nbsp;contact&nbsp;us&nbsp;by&nbsp;writing&nbsp;to&nbsp;the&nbsp;business&nbsp;address&nbsp;given&nbsp;above,&nbsp;by&nbsp;using&nbsp;our&nbsp;website&nbsp;contact&nbsp;form,&nbsp;by&nbsp;email&nbsp;to&nbsp;[<em>email&nbsp;address</em>]&nbsp;or&nbsp;by&nbsp;telephone&nbsp;on&nbsp;[<em>telephone&nbsp;number</em>].</p>
<p>&nbsp;</p>
<p><strong>Drafting&nbsp;notes&nbsp;for&nbsp;free&nbsp;website&nbsp;terms&nbsp;and&nbsp;conditions</strong></p>
<p>Our&nbsp;website&nbsp;terms&nbsp;and&nbsp;conditions&nbsp;template&nbsp;has&nbsp;been&nbsp;designed&nbsp;for&nbsp;use&nbsp;on&nbsp;websites&nbsp;with&nbsp;basic&nbsp;interactive&nbsp;features,&nbsp;such&nbsp;as&nbsp;blogs,&nbsp;bulletin&nbsp;boards&nbsp;and&nbsp;forum-based&nbsp;sites.&nbsp;&nbsp;It&nbsp;includes,&nbsp;amongst&nbsp;other&nbsp;things,&nbsp;a&nbsp;licence&nbsp;specifying&nbsp;how&nbsp;the&nbsp;website&nbsp;may&nbsp;be&nbsp;used,&nbsp;a&nbsp;disclaimer&nbsp;of&nbsp;liability,&nbsp;a&nbsp;statutory&nbsp;disclosures&nbsp;section&nbsp;and&nbsp;rules&nbsp;on&nbsp;user-contributed&nbsp;content.&nbsp;It&nbsp;is&nbsp;an&nbsp;extended&nbsp;version&nbsp;of&nbsp;our&nbsp;website&nbsp;disclaimer&nbsp;document.</p>
<p><strong>Section&nbsp;1&nbsp;-&nbsp;Introduction</strong></p>
<p><em>Section&nbsp;1.2</em></p>
<p>The&nbsp;completed&nbsp;document&nbsp;should&nbsp;be&nbsp;easily&nbsp;accessible&nbsp;on&nbsp;the&nbsp;website,&nbsp;with&nbsp;a&nbsp;link&nbsp;from&nbsp;every&nbsp;page.</p>
<p><em>Section&nbsp;1.3</em></p>
<p>Under&nbsp;what&nbsp;circumstances&nbsp;will&nbsp;users&nbsp;be&nbsp;asked&nbsp;to&nbsp;give&nbsp;their&nbsp;express&nbsp;consent&nbsp;to&nbsp;the&nbsp;terms&nbsp;of&nbsp;this&nbsp;document?</p>
<p>Ideally,&nbsp;from&nbsp;a&nbsp;legal&nbsp;perspective,&nbsp;all&nbsp;users&nbsp;would&nbsp;be&nbsp;asked&nbsp;to&nbsp;expressly&nbsp;agree&nbsp;to&nbsp;the&nbsp;terms&nbsp;of&nbsp;the&nbsp;document.&nbsp;However,&nbsp;in&nbsp;practice,&nbsp;express&nbsp;consent&nbsp;is&nbsp;rarely&nbsp;sought&nbsp;from&nbsp;casual&nbsp;website&nbsp;visitors.&nbsp;On&nbsp;the&nbsp;other&nbsp;hand,&nbsp;it&nbsp;is&nbsp;easy&nbsp;to&nbsp;obtain&nbsp;the&nbsp;express&nbsp;consent&nbsp;of&nbsp;users&nbsp;who&nbsp;register&nbsp;with&nbsp;the&nbsp;website&nbsp;or&nbsp;submit&nbsp;any&nbsp;material&nbsp;to&nbsp;the&nbsp;website,&nbsp;e.g.&nbsp;by&nbsp;clicking&nbsp;"I&nbsp;accept"&nbsp;on&nbsp;an&nbsp;electronic&nbsp;version&nbsp;of&nbsp;the&nbsp;document.&nbsp;You&nbsp;should&nbsp;retain&nbsp;evidence&nbsp;of&nbsp;the&nbsp;acceptance&nbsp;of&nbsp;the&nbsp;document&nbsp;terms&nbsp;by&nbsp;each&nbsp;such&nbsp;user.</p>
<p><em>Section&nbsp;1.4</em></p>
<p>Are&nbsp;there&nbsp;any&nbsp;age&nbsp;restrictions&nbsp;on&nbsp;the&nbsp;use&nbsp;of&nbsp;the&nbsp;website?</p>
<p>What&nbsp;is&nbsp;the&nbsp;minimum&nbsp;age&nbsp;for&nbsp;website&nbsp;users?</p>
<p>The&nbsp;use&nbsp;of&nbsp;websites&nbsp;by&nbsp;minors&nbsp;can&nbsp;be&nbsp;legally&nbsp;problematic.&nbsp;There&nbsp;are&nbsp;a&nbsp;number&nbsp;of&nbsp;different&nbsp;legal&nbsp;issues.&nbsp;For&nbsp;example,&nbsp;under&nbsp;English&nbsp;law,&nbsp;contracts&nbsp;may&nbsp;be&nbsp;unenforceable&nbsp;against&nbsp;minors.&nbsp;Another&nbsp;issue&nbsp;concerns&nbsp;data&nbsp;protection.&nbsp;The&nbsp;law&nbsp;of&nbsp;data&nbsp;protection&nbsp;imposes&nbsp;additional&nbsp;burdens&nbsp;in&nbsp;relation&nbsp;to&nbsp;the&nbsp;processing&nbsp;of&nbsp;any&nbsp;personal&nbsp;data&nbsp;of&nbsp;a&nbsp;minor&nbsp;and&nbsp;personal&nbsp;data&nbsp;provided&nbsp;by&nbsp;a&nbsp;minor.&nbsp;The&nbsp;effects&nbsp;of&nbsp;the&nbsp;law&nbsp;of&nbsp;indecency&nbsp;may&nbsp;also&nbsp;depend&nbsp;upon&nbsp;whether&nbsp;a&nbsp;website&nbsp;is&nbsp;accessible&nbsp;by&nbsp;minors.&nbsp;Obviously,&nbsp;the&nbsp;inclusion&nbsp;of&nbsp;a&nbsp;requirement&nbsp;in&nbsp;your&nbsp;terms&nbsp;and&nbsp;conditions&nbsp;that&nbsp;minors&nbsp;refrain&nbsp;from&nbsp;using&nbsp;a&nbsp;website&nbsp;is&nbsp;no&nbsp;guarantee&nbsp;that&nbsp;they&nbsp;will&nbsp;do&nbsp;so.&nbsp;Where&nbsp;your&nbsp;website&nbsp;is&nbsp;directed&nbsp;at,&nbsp;or&nbsp;likely&nbsp;to&nbsp;be&nbsp;used&nbsp;by,&nbsp;minors,&nbsp;we&nbsp;recommend&nbsp;that&nbsp;you&nbsp;seek&nbsp;specialist&nbsp;legal&nbsp;advice.</p>
<p><em>Section&nbsp;1.5</em></p>
<p>Does&nbsp;the&nbsp;website&nbsp;use&nbsp;cookies&nbsp;(including&nbsp;session&nbsp;cookies&nbsp;and&nbsp;third&nbsp;party&nbsp;cookies)?</p>
<p>What&nbsp;is&nbsp;the&nbsp;title&nbsp;of&nbsp;the&nbsp;document&nbsp;on&nbsp;the&nbsp;website&nbsp;that&nbsp;contains&nbsp;cookie&nbsp;information?</p>
<p>The&nbsp;inclusion&nbsp;of&nbsp;this&nbsp;statement&nbsp;in&nbsp;your&nbsp;website&nbsp;legal&nbsp;documents&nbsp;will&nbsp;not&nbsp;in&nbsp;itself&nbsp;satisfy&nbsp;the&nbsp;requirements&nbsp;of&nbsp;the&nbsp;Privacy&nbsp;and&nbsp;Electronic&nbsp;Communications&nbsp;(EC&nbsp;Directive)&nbsp;Regulations&nbsp;2003&nbsp;(as&nbsp;amended)&nbsp;concerning&nbsp;consent&nbsp;to&nbsp;the&nbsp;use&nbsp;of&nbsp;cookies.&nbsp;Guidance&nbsp;concerning&nbsp;methods&nbsp;of&nbsp;obtaining&nbsp;such&nbsp;consent&nbsp;is&nbsp;included&nbsp;on&nbsp;the&nbsp;Information&nbsp;Commissioner's&nbsp;website&nbsp;(http://www.ico.gov.uk).</p>
<p><strong>Section&nbsp;3&nbsp;-&nbsp;Copyright&nbsp;notice</strong></p>
<p><em>Section&nbsp;3.1</em></p>
<p>What&nbsp;was&nbsp;the&nbsp;year&nbsp;of&nbsp;first&nbsp;publication&nbsp;of&nbsp;the&nbsp;relevant&nbsp;copyright&nbsp;material&nbsp;(or&nbsp;the&nbsp;range&nbsp;of&nbsp;years)?&nbsp;Who&nbsp;is&nbsp;the&nbsp;principal&nbsp;owner&nbsp;of&nbsp;copyright&nbsp;in&nbsp;the&nbsp;website?</p>
<p><strong>Section&nbsp;4&nbsp;-&nbsp;Licence&nbsp;to&nbsp;use&nbsp;website</strong></p>
<p>The&nbsp;scope&nbsp;of&nbsp;the&nbsp;licence&nbsp;to&nbsp;use&nbsp;will&nbsp;vary&nbsp;with&nbsp;each&nbsp;site.&nbsp;Consider&nbsp;carefully&nbsp;exactly&nbsp;what&nbsp;your&nbsp;users&nbsp;should&nbsp;be&nbsp;allowed&nbsp;to&nbsp;do&nbsp;with&nbsp;your&nbsp;website&nbsp;and&nbsp;material&nbsp;on&nbsp;your&nbsp;website.</p>
<p><em>Section&nbsp;4.1</em></p>
<p>(d)&nbsp;-&nbsp;Will&nbsp;audio&nbsp;and/or&nbsp;video&nbsp;files&nbsp;be&nbsp;published&nbsp;on&nbsp;the&nbsp;website?</p>
<p>(e)&nbsp;-&nbsp;Will&nbsp;the&nbsp;website&nbsp;make&nbsp;available&nbsp;any&nbsp;dynamic&nbsp;services&nbsp;to&nbsp;users?&nbsp;Describe&nbsp;the&nbsp;website&nbsp;services&nbsp;in&nbsp;question.</p>
<p><em>Section&nbsp;4.3</em></p>
<p>Consider&nbsp;whether&nbsp;to&nbsp;include&nbsp;this&nbsp;element&nbsp;in&nbsp;the&nbsp;document.</p>
<p>For&nbsp;what&nbsp;purposes&nbsp;may&nbsp;the&nbsp;website&nbsp;be&nbsp;used?</p>
<p><em>Section&nbsp;4.6</em></p>
<p>Are&nbsp;users&nbsp;permitted&nbsp;to&nbsp;redistribute&nbsp;any&nbsp;specific&nbsp;content&nbsp;from&nbsp;the&nbsp;website&nbsp;(e.g.&nbsp;newsletters)?</p>
<p>What&nbsp;types&nbsp;of&nbsp;content&nbsp;are&nbsp;redistributable?&nbsp;In&nbsp;what&nbsp;formats&nbsp;may&nbsp;redistributable&nbsp;content&nbsp;be&nbsp;redistributed?&nbsp;To&nbsp;whom&nbsp;may&nbsp;redistributable&nbsp;content&nbsp;be&nbsp;redistributed?</p>
<p><strong>Section&nbsp;5&nbsp;-&nbsp;Acceptable&nbsp;use</strong></p>
<p><em>Section&nbsp;5.1</em></p>
<p>(e)&nbsp;-&nbsp;Should&nbsp;all&nbsp;automated&nbsp;interactions&nbsp;with&nbsp;the&nbsp;website&nbsp;be&nbsp;prohibited?</p>
<p>(f)&nbsp;-&nbsp;Will&nbsp;the&nbsp;website&nbsp;incorporate&nbsp;a&nbsp;robots.txt&nbsp;file?</p>
<p>(g)&nbsp;-&nbsp;Should&nbsp;users&nbsp;be&nbsp;prohibited&nbsp;from&nbsp;using&nbsp;the&nbsp;website&nbsp;for&nbsp;direct&nbsp;marketing&nbsp;activity?</p>
<p><em>Section&nbsp;5.2</em></p>
<p>Should&nbsp;the&nbsp;use&nbsp;of&nbsp;data&nbsp;collected&nbsp;from&nbsp;the&nbsp;website&nbsp;to&nbsp;contact&nbsp;people&nbsp;and&nbsp;businesses&nbsp;be&nbsp;prohibited?</p>
<p><em>Section&nbsp;5.3</em></p>
<p>What&nbsp;standard&nbsp;of&nbsp;veracity&nbsp;etc&nbsp;should&nbsp;user-submitted&nbsp;content&nbsp;meet?</p>
<p><strong>Section&nbsp;6&nbsp;-&nbsp;Registration&nbsp;and&nbsp;accounts</strong></p>
<p><em>Section&nbsp;6.1</em></p>
<p>Do&nbsp;any&nbsp;eligibility&nbsp;criteria&nbsp;apply&nbsp;to&nbsp;account&nbsp;registration?</p>
<p>What&nbsp;eligibility&nbsp;criteria&nbsp;apply?</p>
<p><em>Section&nbsp;6.2</em></p>
<p>How&nbsp;do&nbsp;users&nbsp;register&nbsp;with&nbsp;the&nbsp;website?</p>
<p><em>Section&nbsp;6.4</em></p>
<p>Are&nbsp;users&nbsp;permitted&nbsp;to&nbsp;use&nbsp;another&nbsp;person's&nbsp;account&nbsp;on&nbsp;the&nbsp;website&nbsp;with&nbsp;the&nbsp;permission&nbsp;of&nbsp;that&nbsp;other&nbsp;person?</p>
<p><strong>Section&nbsp;7&nbsp;-&nbsp;User&nbsp;IDs&nbsp;and&nbsp;passwords</strong></p>
<p><em>Section&nbsp;7.1</em></p>
<p>How&nbsp;will&nbsp;users'&nbsp;login&nbsp;details&nbsp;be&nbsp;generated?</p>
<p><strong>Section&nbsp;8&nbsp;-&nbsp;Cancellation&nbsp;and&nbsp;suspension&nbsp;of&nbsp;account</strong></p>
<p><em>Section&nbsp;8.1</em></p>
<p>Which&nbsp;of&nbsp;these&nbsp;general&nbsp;rights&nbsp;over&nbsp;user&nbsp;accounts&nbsp;does&nbsp;the&nbsp;website&nbsp;operator&nbsp;have?</p>
<p><em>Section&nbsp;8.2</em></p>
<p>How&nbsp;can&nbsp;a&nbsp;user&nbsp;cancel&nbsp;his&nbsp;or&nbsp;her&nbsp;account&nbsp;on&nbsp;the&nbsp;website?</p>
<p><strong>Section&nbsp;9&nbsp;-&nbsp;Your&nbsp;content:&nbsp;licence</strong></p>
<p><em>Section&nbsp;9.2</em></p>
<p>What&nbsp;type&nbsp;of&nbsp;licence&nbsp;do&nbsp;users&nbsp;grant&nbsp;to&nbsp;the&nbsp;website&nbsp;operator?&nbsp;What&nbsp;does&nbsp;the&nbsp;licence&nbsp;allow&nbsp;the&nbsp;website&nbsp;operator&nbsp;to&nbsp;do&nbsp;with&nbsp;user&nbsp;content?</p>
<p><em>Section&nbsp;9.4</em></p>
<p>Should&nbsp;the&nbsp;website&nbsp;operator&nbsp;be&nbsp;granted&nbsp;a&nbsp;right&nbsp;to&nbsp;bring&nbsp;proceedings&nbsp;in&nbsp;respect&nbsp;of&nbsp;third&nbsp;party&nbsp;infringements?</p>
<p><em>Section&nbsp;9.5</em></p>
<p>Should&nbsp;users&nbsp;be&nbsp;asked&nbsp;to&nbsp;waive&nbsp;their&nbsp;moral&nbsp;rights&nbsp;(such&nbsp;as&nbsp;the&nbsp;right&nbsp;of&nbsp;paternity&nbsp;and&nbsp;the&nbsp;right&nbsp;to&nbsp;object&nbsp;to&nbsp;derogatory&nbsp;treatment)&nbsp;in&nbsp;the&nbsp;content&nbsp;they&nbsp;submit&nbsp;to&nbsp;the&nbsp;website?</p>
<p><em>Section&nbsp;9.6</em></p>
<p>Can&nbsp;users&nbsp;edit&nbsp;their&nbsp;own&nbsp;content&nbsp;after&nbsp;it&nbsp;has&nbsp;been&nbsp;posted&nbsp;to&nbsp;the&nbsp;website?</p>
<p><strong>Section&nbsp;10&nbsp;-&nbsp;Your&nbsp;content:&nbsp;rules</strong></p>
<p><em>Section&nbsp;10.2</em></p>
<p>This&nbsp;very&nbsp;general&nbsp;prohibition&nbsp;against&nbsp;unlawful&nbsp;user&nbsp;content&nbsp;may&nbsp;be&nbsp;supplemented&nbsp;by&nbsp;rules&nbsp;relating&nbsp;to&nbsp;specific&nbsp;kinds&nbsp;of&nbsp;illegality,&nbsp;as&nbsp;well&nbsp;as&nbsp;prohibitions&nbsp;upon&nbsp;lawful&nbsp;but&nbsp;undesirable&nbsp;content.</p>
<p><em>Section&nbsp;10.3</em></p>
<p>(f)&nbsp;-&nbsp;Do&nbsp;you&nbsp;want&nbsp;to&nbsp;expressly&nbsp;prohibit&nbsp;the&nbsp;publication&nbsp;by&nbsp;users&nbsp;of&nbsp;information&nbsp;about&nbsp;how&nbsp;to&nbsp;commit&nbsp;crimes&nbsp;and&nbsp;the&nbsp;promotion&nbsp;of&nbsp;criminal&nbsp;activities?</p>
<p>(l)&nbsp;-&nbsp;Should&nbsp;the&nbsp;depiction&nbsp;of&nbsp;violence&nbsp;be&nbsp;prohibited?&nbsp;Should&nbsp;the&nbsp;prohibition&nbsp;on&nbsp;depicting&nbsp;violence&nbsp;be&nbsp;limited&nbsp;to&nbsp;explicit&nbsp;etc&nbsp;violence?</p>
<p>(m)&nbsp;-&nbsp;Should&nbsp;pornographic&nbsp;material&nbsp;be&nbsp;prohibited?&nbsp;Should&nbsp;the&nbsp;prohibition&nbsp;on&nbsp;pornographic&nbsp;material&nbsp;be&nbsp;supplemented&nbsp;with&nbsp;a&nbsp;prohibition&nbsp;on&nbsp;lewd,&nbsp;suggestive&nbsp;or&nbsp;sexually&nbsp;explicit&nbsp;material?</p>
<p>(n)&nbsp;-&nbsp;Should&nbsp;untrue,&nbsp;false,&nbsp;inaccurate&nbsp;or&nbsp;misleading&nbsp;content&nbsp;be&nbsp;prohibited?</p>
<p>(o)&nbsp;-&nbsp;Should&nbsp;potentially&nbsp;dangerous&nbsp;advice&nbsp;be&nbsp;prohibited?</p>
<p>(p)&nbsp;-&nbsp;Should&nbsp;spam&nbsp;be&nbsp;prohibited?</p>
<p>(q)&nbsp;-&nbsp;Should&nbsp;offensive&nbsp;etc&nbsp;material&nbsp;be&nbsp;prohibited?</p>
<p>(r)&nbsp;-&nbsp;Should&nbsp;annoying&nbsp;etc&nbsp;material&nbsp;be&nbsp;prohibited?</p>
<p><strong>Section&nbsp;12&nbsp;-&nbsp;Limitations&nbsp;and&nbsp;exclusions&nbsp;of&nbsp;liability</strong></p>
<p>Contractual&nbsp;limitations&nbsp;and&nbsp;exclusions&nbsp;of&nbsp;liability&nbsp;are&nbsp;regulated&nbsp;and&nbsp;controlled&nbsp;by&nbsp;law,&nbsp;and&nbsp;the&nbsp;courts&nbsp;may&nbsp;rule&nbsp;that&nbsp;particular&nbsp;limitations&nbsp;and&nbsp;exclusions&nbsp;of&nbsp;liability&nbsp;in&nbsp;contracts&nbsp;are&nbsp;unenforceable.</p>
<p>The&nbsp;courts&nbsp;are&nbsp;particularly&nbsp;likely&nbsp;to&nbsp;intervene&nbsp;where&nbsp;a&nbsp;party&nbsp;is&nbsp;seeking&nbsp;to&nbsp;rely&nbsp;on&nbsp;a&nbsp;limitation&nbsp;or&nbsp;exclusion&nbsp;of&nbsp;liability&nbsp;in&nbsp;its&nbsp;standard&nbsp;terms&nbsp;and&nbsp;conditions,&nbsp;but&nbsp;will&nbsp;also&nbsp;sometimes&nbsp;intervene&nbsp;where&nbsp;a&nbsp;term&nbsp;has&nbsp;been&nbsp;individually&nbsp;negotiated.</p>
<p>The&nbsp;courts&nbsp;may&nbsp;be&nbsp;more&nbsp;likely&nbsp;to&nbsp;rule&nbsp;that&nbsp;provisions&nbsp;excluding&nbsp;liability,&nbsp;as&nbsp;opposed&nbsp;to&nbsp;those&nbsp;merely&nbsp;limiting&nbsp;liability,&nbsp;are&nbsp;unenforceable.</p>
<p>If&nbsp;there&nbsp;is&nbsp;a&nbsp;risk&nbsp;that&nbsp;any&nbsp;particular&nbsp;limitation&nbsp;or&nbsp;exclusion&nbsp;of&nbsp;liability&nbsp;will&nbsp;be&nbsp;found&nbsp;to&nbsp;be&nbsp;unenforceable&nbsp;by&nbsp;the&nbsp;courts,&nbsp;that&nbsp;provision&nbsp;should&nbsp;be&nbsp;drafted&nbsp;as&nbsp;an&nbsp;independent&nbsp;term,&nbsp;and&nbsp;be&nbsp;numbered&nbsp;separately&nbsp;from&nbsp;the&nbsp;other&nbsp;provisions.</p>
<p>It&nbsp;may&nbsp;improve&nbsp;the&nbsp;chances&nbsp;of&nbsp;a&nbsp;limitation&nbsp;or&nbsp;exclusion&nbsp;of&nbsp;liability&nbsp;being&nbsp;found&nbsp;to&nbsp;be&nbsp;enforceable&nbsp;if&nbsp;the&nbsp;party&nbsp;seeking&nbsp;to&nbsp;rely&nbsp;upon&nbsp;it&nbsp;specifically&nbsp;drew&nbsp;it&nbsp;to&nbsp;the&nbsp;attention&nbsp;of&nbsp;the&nbsp;other&nbsp;party&nbsp;before&nbsp;the&nbsp;contract&nbsp;was&nbsp;entered&nbsp;into.</p>
<p>Exclusions&nbsp;and&nbsp;limitations&nbsp;of&nbsp;liability&nbsp;in&nbsp;UK&nbsp;contracts&nbsp;are&nbsp;primarily&nbsp;regulated&nbsp;by&nbsp;the&nbsp;Unfair&nbsp;Contract&nbsp;Terms&nbsp;Act&nbsp;1977&nbsp;("UCTA").</p>
<p>Contracts&nbsp;regulated&nbsp;by&nbsp;UCTA&nbsp;cannot&nbsp;exclude&nbsp;or&nbsp;restrict&nbsp;a&nbsp;party's&nbsp;liability&nbsp;for&nbsp;death&nbsp;or&nbsp;personal&nbsp;injury&nbsp;resulting&nbsp;from&nbsp;negligence&nbsp;(Section&nbsp;2(1),&nbsp;UCTA).</p>
<p>Except&nbsp;insofar&nbsp;as&nbsp;the&nbsp;relevant&nbsp;term&nbsp;satisfies&nbsp;the&nbsp;requirements&nbsp;of&nbsp;reasonableness,&nbsp;such&nbsp;contracts&nbsp;cannot&nbsp;exclude&nbsp;or&nbsp;restrict&nbsp;liability:&nbsp;(i)&nbsp;for&nbsp;negligence&nbsp;(which&nbsp;includes&nbsp;a&nbsp;breach&nbsp;of&nbsp;an&nbsp;express&nbsp;or&nbsp;implied&nbsp;contractual&nbsp;obligation&nbsp;to&nbsp;take&nbsp;reasonable&nbsp;care&nbsp;or&nbsp;exercise&nbsp;reasonable&nbsp;skill)&nbsp;(Section&nbsp;2(2),&nbsp;UCTA);&nbsp;or&nbsp;(ii)&nbsp;for&nbsp;misrepresentation&nbsp;(Section&nbsp;3,&nbsp;Misrepresentation&nbsp;Act&nbsp;1967).</p>
<p>In&nbsp;addition,&nbsp;if&nbsp;a&nbsp;contract&nbsp;is&nbsp;regulated&nbsp;by&nbsp;UCTA,&nbsp;and&nbsp;one&nbsp;of&nbsp;the&nbsp;parties&nbsp;is&nbsp;dealing&nbsp;on&nbsp;the&nbsp;other's&nbsp;written&nbsp;standard&nbsp;terms&nbsp;of&nbsp;business,&nbsp;then&nbsp;except&nbsp;insofar&nbsp;as&nbsp;the&nbsp;relevant&nbsp;contractual&nbsp;term&nbsp;satisfies&nbsp;the&nbsp;requirements&nbsp;of&nbsp;reasonableness&nbsp;the&nbsp;other&nbsp;party&nbsp;cannot:&nbsp;(i)&nbsp;exclude&nbsp;or&nbsp;restrict&nbsp;his&nbsp;liability&nbsp;in&nbsp;respect&nbsp;of&nbsp;a&nbsp;breach&nbsp;of&nbsp;contract;&nbsp;or&nbsp;(ii)&nbsp;claim&nbsp;to&nbsp;be&nbsp;entitled&nbsp;to&nbsp;render&nbsp;a&nbsp;contractual&nbsp;performance&nbsp;substantially&nbsp;different&nbsp;from&nbsp;that&nbsp;which&nbsp;was&nbsp;reasonably&nbsp;expected&nbsp;of&nbsp;him;&nbsp;or&nbsp;(iii)&nbsp;claim&nbsp;to&nbsp;be&nbsp;entitled,&nbsp;in&nbsp;respect&nbsp;of&nbsp;the&nbsp;whole&nbsp;or&nbsp;any&nbsp;part&nbsp;of&nbsp;his&nbsp;contractual&nbsp;obligation,&nbsp;to&nbsp;render&nbsp;no&nbsp;contractual&nbsp;performance&nbsp;at&nbsp;all&nbsp;(see&nbsp;Section&nbsp;3,&nbsp;UCTA).</p>
<p>UCTA&nbsp;includes&nbsp;various&nbsp;other&nbsp;restrictions,&nbsp;particularly&nbsp;in&nbsp;the&nbsp;case&nbsp;of&nbsp;contracts&nbsp;for&nbsp;the&nbsp;sale&nbsp;of&nbsp;goods&nbsp;and&nbsp;contracts&nbsp;under&nbsp;which&nbsp;possession&nbsp;or&nbsp;ownership&nbsp;of&nbsp;goods&nbsp;passes.</p>
<p>If&nbsp;you&nbsp;wish&nbsp;to&nbsp;try&nbsp;to&nbsp;limit/exclude&nbsp;for&nbsp;liability&nbsp;in&nbsp;respect&nbsp;of&nbsp;reckless,&nbsp;deliberate,&nbsp;personal&nbsp;and/or&nbsp;repudiatory&nbsp;breaches&nbsp;of&nbsp;contract,&nbsp;you&nbsp;should&nbsp;specify&nbsp;this&nbsp;in&nbsp;relation&nbsp;to&nbsp;the&nbsp;relevant&nbsp;provision&nbsp;(for&nbsp;example,&nbsp;using&nbsp;the&nbsp;following&nbsp;wording:&nbsp;"The&nbsp;limitations&nbsp;and&nbsp;exclusions&nbsp;of&nbsp;liability&nbsp;in&nbsp;this&nbsp;Clause&nbsp;[number]&nbsp;will&nbsp;apply&nbsp;whether&nbsp;or&nbsp;not&nbsp;the&nbsp;liability&nbsp;in&nbsp;question&nbsp;arises&nbsp;out&nbsp;of&nbsp;any&nbsp;reckless,&nbsp;deliberate,&nbsp;personal&nbsp;and/or&nbsp;repudiatory&nbsp;conduct&nbsp;or&nbsp;breach&nbsp;of&nbsp;contract").&nbsp;In&nbsp;many&nbsp;circumstances,&nbsp;however,&nbsp;the&nbsp;courts&nbsp;will&nbsp;find&nbsp;these&nbsp;types&nbsp;of&nbsp;limitations&nbsp;and&nbsp;exclusions&nbsp;to&nbsp;be&nbsp;unenforceable.</p>
<p>Somewhat&nbsp;different&nbsp;rules&nbsp;apply&nbsp;to&nbsp;limitations&nbsp;of&nbsp;liability&nbsp;in&nbsp;contracts&nbsp;with&nbsp;consumers,&nbsp;and&nbsp;these&nbsp;provisions&nbsp;should&nbsp;not&nbsp;be&nbsp;used&nbsp;in&nbsp;relation&nbsp;to&nbsp;such&nbsp;contracts.</p>
<p>These&nbsp;guidance&nbsp;notes&nbsp;provide&nbsp;a&nbsp;very&nbsp;incomplete&nbsp;and&nbsp;basic&nbsp;overview&nbsp;of&nbsp;a&nbsp;complex&nbsp;subject.&nbsp;Accordingly,&nbsp;you&nbsp;should&nbsp;take&nbsp;legal&nbsp;advice&nbsp;if&nbsp;you&nbsp;may&nbsp;wish&nbsp;to&nbsp;rely&nbsp;upon&nbsp;a&nbsp;limitation&nbsp;or&nbsp;exclusion&nbsp;of&nbsp;liability.</p>
<p><em>Section&nbsp;12.1</em></p>
<p>Do&nbsp;not&nbsp;delete&nbsp;this&nbsp;provision&nbsp;(except&nbsp;upon&nbsp;legal&nbsp;advice).&nbsp;Without&nbsp;this&nbsp;provision,&nbsp;the&nbsp;specific&nbsp;limitations&nbsp;and&nbsp;exclusions&nbsp;of&nbsp;liability&nbsp;in&nbsp;the&nbsp;document&nbsp;are&nbsp;more&nbsp;likely&nbsp;to&nbsp;be&nbsp;unenforceable.</p>
<p><em>Section&nbsp;12.3</em></p>
<p>Do&nbsp;you&nbsp;want&nbsp;to&nbsp;attempt&nbsp;to&nbsp;exclude&nbsp;all&nbsp;liability&nbsp;for&nbsp;free&nbsp;services&nbsp;and&nbsp;information?</p>
<p>This&nbsp;sort&nbsp;of&nbsp;exclusion&nbsp;is&nbsp;quite&nbsp;common,&nbsp;but&nbsp;unlikely&nbsp;to&nbsp;be&nbsp;enforceable&nbsp;in&nbsp;court.</p>
<p><em>Section&nbsp;12.7</em></p>
<p>"Consequential&nbsp;loss"&nbsp;has&nbsp;a&nbsp;special&nbsp;meaning&nbsp;in&nbsp;English&nbsp;law:&nbsp;it&nbsp;means&nbsp;any&nbsp;loss&nbsp;that,&nbsp;whilst&nbsp;not&nbsp;arising&nbsp;naturally&nbsp;from&nbsp;the&nbsp;breach,&nbsp;was&nbsp;specifically&nbsp;in&nbsp;the&nbsp;contemplation&nbsp;of&nbsp;the&nbsp;parties&nbsp;when&nbsp;the&nbsp;contract&nbsp;was&nbsp;made.</p>
<p><em>Section&nbsp;12.8</em></p>
<p>If&nbsp;the&nbsp;website&nbsp;operator&nbsp;is&nbsp;a&nbsp;limited&nbsp;liability&nbsp;entity&nbsp;(e.g.&nbsp;a&nbsp;limited&nbsp;company),&nbsp;do&nbsp;you&nbsp;want&nbsp;to&nbsp;expressly&nbsp;exclude&nbsp;liability&nbsp;on&nbsp;the&nbsp;part&nbsp;of&nbsp;officers&nbsp;and&nbsp;employees?&nbsp;</p>
<p><strong>Section&nbsp;14&nbsp;-&nbsp;Variation</strong></p>
<p>Changes&nbsp;to&nbsp;legal&nbsp;documents&nbsp;published&nbsp;on&nbsp;a&nbsp;website&nbsp;will&nbsp;not&nbsp;generally&nbsp;be&nbsp;retrospectively&nbsp;effective,&nbsp;and&nbsp;variations&nbsp;without&nbsp;notice&nbsp;to&nbsp;and/or&nbsp;consent&nbsp;from&nbsp;relevant&nbsp;users&nbsp;may&nbsp;be&nbsp;ineffective.</p>
<p><em>Section&nbsp;14.2</em></p>
<p>Will&nbsp;website&nbsp;users&nbsp;be&nbsp;notified&nbsp;of&nbsp;changes&nbsp;to&nbsp;the&nbsp;document?</p>
<p><em>Section&nbsp;14.3</em></p>
<p>Will&nbsp;registered&nbsp;users&nbsp;be&nbsp;required&nbsp;to&nbsp;consent&nbsp;to&nbsp;variations?</p>
<p><strong>Section&nbsp;17&nbsp;-&nbsp;Third&nbsp;party&nbsp;rights</strong></p>
<p>This&nbsp;provision&nbsp;is&nbsp;designed&nbsp;to&nbsp;exclude&nbsp;any&nbsp;rights&nbsp;a&nbsp;third&nbsp;party&nbsp;may&nbsp;have&nbsp;under&nbsp;the&nbsp;Contracts&nbsp;(Rights&nbsp;of&nbsp;Third&nbsp;Parties)&nbsp;Act&nbsp;1999.</p>
<p><strong>Section&nbsp;18&nbsp;-&nbsp;Entire&nbsp;agreement</strong></p>
<p><em>Section&nbsp;18.1</em></p>
<p>What&nbsp;other&nbsp;documents&nbsp;govern&nbsp;the&nbsp;use&nbsp;of&nbsp;the&nbsp;website?</p>
<p><strong>Section&nbsp;19&nbsp;-&nbsp;Law&nbsp;and&nbsp;jurisdiction</strong></p>
<p>The&nbsp;questions&nbsp;of&nbsp;which&nbsp;law&nbsp;governs&nbsp;a&nbsp;document,&nbsp;and&nbsp;where&nbsp;disputes&nbsp;relating&nbsp;to&nbsp;the&nbsp;document&nbsp;may&nbsp;be&nbsp;litigated,&nbsp;are&nbsp;two&nbsp;distinct&nbsp;questions.</p>
<p><em>Section&nbsp;19.1</em></p>
<p>Which&nbsp;law&nbsp;should&nbsp;govern&nbsp;the&nbsp;document?</p>
<p>This&nbsp;document&nbsp;has&nbsp;been&nbsp;drafted&nbsp;to&nbsp;comply&nbsp;with&nbsp;English&nbsp;law,&nbsp;and&nbsp;the&nbsp;governing&nbsp;law&nbsp;provision&nbsp;should&nbsp;not&nbsp;be&nbsp;changed&nbsp;without&nbsp;obtaining&nbsp;expert&nbsp;advice&nbsp;from&nbsp;a&nbsp;lawyer&nbsp;qualified&nbsp;in&nbsp;the&nbsp;appropriate&nbsp;jurisdiction.&nbsp;In&nbsp;some&nbsp;circumstances&nbsp;the&nbsp;courts&nbsp;will&nbsp;apply&nbsp;provisions&nbsp;of&nbsp;their&nbsp;local&nbsp;law,&nbsp;such&nbsp;as&nbsp;local&nbsp;competition&nbsp;law&nbsp;or&nbsp;consumer&nbsp;protection&nbsp;law,&nbsp;irrespective&nbsp;of&nbsp;a&nbsp;choice&nbsp;of&nbsp;law&nbsp;clause.</p>
<p><em>Section&nbsp;19.2</em></p>
<p>Should&nbsp;the&nbsp;jurisdiction&nbsp;granted&nbsp;be&nbsp;exclusive&nbsp;or&nbsp;non-exclusive?&nbsp;Choose&nbsp;"non-exclusive"&nbsp;jurisdiction&nbsp;if&nbsp;you&nbsp;may&nbsp;want&nbsp;to&nbsp;enforce&nbsp;the&nbsp;terms&nbsp;and&nbsp;conditions&nbsp;against&nbsp;users&nbsp;outside&nbsp;England&nbsp;and&nbsp;Wales.&nbsp;Otherwise,&nbsp;choose&nbsp;"exclusive&nbsp;jurisdiction".&nbsp;The&nbsp;courts&nbsp;of&nbsp;which&nbsp;country&nbsp;or&nbsp;jurisdiction&nbsp;should&nbsp;adjudicate&nbsp;disputes&nbsp;under&nbsp;the&nbsp;document?</p>
<p>In&nbsp;some&nbsp;circumstances&nbsp;your&nbsp;jurisdiction&nbsp;clause&nbsp;may&nbsp;be&nbsp;overridden&nbsp;by&nbsp;the&nbsp;courts.</p>
<p><strong>Section&nbsp;20&nbsp;-&nbsp;Statutory&nbsp;and&nbsp;regulatory&nbsp;disclosures</strong></p>
<p>Do&nbsp;the&nbsp;Electronic&nbsp;Commerce&nbsp;(EC&nbsp;Directive)&nbsp;Regulations&nbsp;2002&nbsp;apply&nbsp;to&nbsp;the&nbsp;website&nbsp;or&nbsp;is&nbsp;the&nbsp;website&nbsp;operator&nbsp;registered&nbsp;for&nbsp;VAT?</p>
<p>This&nbsp;section&nbsp;can&nbsp;be&nbsp;deleted&nbsp;where&nbsp;website&nbsp;operator&nbsp;is&nbsp;not&nbsp;registered&nbsp;for&nbsp;VAT&nbsp;and&nbsp;the&nbsp;Electronic&nbsp;Commerce&nbsp;(EC&nbsp;Directive)&nbsp;Regulations&nbsp;2002&nbsp;do&nbsp;not&nbsp;apply.&nbsp;Generally,&nbsp;those&nbsp;Regulations&nbsp;will&nbsp;apply&nbsp;unless&nbsp;a&nbsp;website&nbsp;is&nbsp;entirely&nbsp;non-commercial,&nbsp;i.e.&nbsp;where&nbsp;a&nbsp;website&nbsp;does&nbsp;not&nbsp;offer&nbsp;any&nbsp;goods&nbsp;or&nbsp;services&nbsp;and&nbsp;does&nbsp;not&nbsp;involve&nbsp;any&nbsp;remuneration&nbsp;(which&nbsp;includes&nbsp;remuneration&nbsp;for&nbsp;carrying&nbsp;AdSense&nbsp;or&nbsp;other&nbsp;advertising).</p>
<p><em>Section&nbsp;20.1</em></p>
<p>Is&nbsp;the&nbsp;website&nbsp;operator&nbsp;registered&nbsp;in&nbsp;a&nbsp;trade&nbsp;or&nbsp;similar&nbsp;register&nbsp;that&nbsp;is&nbsp;available&nbsp;to&nbsp;the&nbsp;public?</p>
<p>What&nbsp;is&nbsp;the&nbsp;name&nbsp;of&nbsp;the&nbsp;trade&nbsp;register?&nbsp;At&nbsp;what&nbsp;URL&nbsp;can&nbsp;the&nbsp;trade&nbsp;register&nbsp;be&nbsp;found?&nbsp;What&nbsp;is&nbsp;the&nbsp;website&nbsp;operator's&nbsp;registration&nbsp;number?</p>
<p>The&nbsp;Electronic&nbsp;Commerce&nbsp;(EC&nbsp;Directive)&nbsp;Regulations&nbsp;2002&nbsp;provide&nbsp;that&nbsp;if&nbsp;you&nbsp;are&nbsp;"registered&nbsp;in&nbsp;a&nbsp;trade&nbsp;or&nbsp;similar&nbsp;register&nbsp;available&nbsp;to&nbsp;the&nbsp;public",&nbsp;you&nbsp;must&nbsp;provide&nbsp;"details&nbsp;of&nbsp;the&nbsp;register&nbsp;in&nbsp;which&nbsp;the&nbsp;service&nbsp;provider&nbsp;is&nbsp;entered&nbsp;and&nbsp;his&nbsp;registration&nbsp;number,&nbsp;or&nbsp;equivalent&nbsp;means&nbsp;of&nbsp;identification&nbsp;in&nbsp;that&nbsp;register".</p>
<p><em>Section&nbsp;20.2</em></p>
<p>Is&nbsp;the&nbsp;website&nbsp;operator&nbsp;subject&nbsp;to&nbsp;an&nbsp;authorisation&nbsp;scheme&nbsp;(e.g.&nbsp;under&nbsp;financial&nbsp;services&nbsp;legislation)?</p>
<p>What&nbsp;is&nbsp;the&nbsp;name&nbsp;of&nbsp;the&nbsp;authorisation&nbsp;scheme&nbsp;to&nbsp;which&nbsp;the&nbsp;website&nbsp;operator&nbsp;is&nbsp;subject?&nbsp;What&nbsp;authority&nbsp;supervises&nbsp;the&nbsp;authorisation&nbsp;scheme?</p>
<p>The&nbsp;Electronic&nbsp;Commerce&nbsp;(EC&nbsp;Directive)&nbsp;Regulations&nbsp;2002&nbsp;provide&nbsp;that&nbsp;"where&nbsp;the&nbsp;provision&nbsp;of&nbsp;the&nbsp;service&nbsp;is&nbsp;subject&nbsp;to&nbsp;an&nbsp;authorisation&nbsp;scheme"&nbsp;you&nbsp;must&nbsp;provide&nbsp;"the&nbsp;particulars&nbsp;of&nbsp;the&nbsp;relevant&nbsp;supervisory&nbsp;authority".</p>
<p><em>Section&nbsp;20.3</em></p>
<p>Is&nbsp;the&nbsp;service&nbsp;provider&nbsp;a&nbsp;member&nbsp;of&nbsp;a&nbsp;regulated&nbsp;profession&nbsp;(e.g.&nbsp;solicitors)?</p>
<p>What&nbsp;is&nbsp;the&nbsp;website&nbsp;operator's&nbsp;professional&nbsp;title?&nbsp;Which&nbsp;professional&nbsp;body&nbsp;regulates&nbsp;the&nbsp;website&nbsp;operator?&nbsp;In&nbsp;which&nbsp;jurisdiction&nbsp;was&nbsp;the&nbsp;professional&nbsp;title&nbsp;granted?&nbsp;What&nbsp;is&nbsp;the&nbsp;name&nbsp;of&nbsp;the&nbsp;document&nbsp;containing&nbsp;the&nbsp;rules&nbsp;governing&nbsp;the&nbsp;profession?&nbsp;At&nbsp;what&nbsp;URL&nbsp;can&nbsp;the&nbsp;rules&nbsp;be&nbsp;found?</p>
<p>The&nbsp;Electronic&nbsp;Commerce&nbsp;(EC&nbsp;Directive)&nbsp;Regulations&nbsp;2002&nbsp;provide&nbsp;that&nbsp;if&nbsp;"the&nbsp;service&nbsp;provider&nbsp;exercises&nbsp;a&nbsp;regulated&nbsp;profession",&nbsp;it&nbsp;must&nbsp;provide&nbsp;"(i)&nbsp;the&nbsp;details&nbsp;of&nbsp;any&nbsp;professional&nbsp;body&nbsp;or&nbsp;similar&nbsp;institution&nbsp;with&nbsp;which&nbsp;the&nbsp;service&nbsp;provider&nbsp;is&nbsp;registered;&nbsp;(ii)&nbsp;his&nbsp;professional&nbsp;title&nbsp;and&nbsp;the&nbsp;member&nbsp;State&nbsp;where&nbsp;that&nbsp;title&nbsp;has&nbsp;been&nbsp;granted;&nbsp;(iii)&nbsp;a&nbsp;reference&nbsp;to&nbsp;the&nbsp;professional&nbsp;rules&nbsp;applicable&nbsp;to&nbsp;the&nbsp;service&nbsp;provider&nbsp;in&nbsp;the&nbsp;member&nbsp;State&nbsp;of&nbsp;establishment&nbsp;and&nbsp;the&nbsp;means&nbsp;to&nbsp;access&nbsp;them".</p>
<p><em>Section&nbsp;20.4</em></p>
<p>Does&nbsp;the&nbsp;website&nbsp;operator&nbsp;subscribe&nbsp;to&nbsp;any&nbsp;codes&nbsp;of&nbsp;conduct?</p>
<p>Identify&nbsp;the&nbsp;codes&nbsp;of&nbsp;conduct&nbsp;in&nbsp;question.&nbsp;Where&nbsp;can&nbsp;the&nbsp;codes&nbsp;be&nbsp;viewed?</p>
<p>The&nbsp;Electronic&nbsp;Commerce&nbsp;(EC&nbsp;Directive)&nbsp;Regulations&nbsp;2002&nbsp;provide&nbsp;that&nbsp;"a&nbsp;service&nbsp;provider&nbsp;shall&nbsp;indicate&nbsp;which&nbsp;relevant&nbsp;codes&nbsp;of&nbsp;conduct&nbsp;he&nbsp;subscribes&nbsp;to&nbsp;and&nbsp;give&nbsp;information&nbsp;on&nbsp;how&nbsp;those&nbsp;codes&nbsp;can&nbsp;be&nbsp;consulted&nbsp;electronically".</p>
<p><em>Section&nbsp;20.5</em></p>
<p>Is&nbsp;the&nbsp;website&nbsp;operator&nbsp;registered&nbsp;for&nbsp;VAT?</p>
<p>What&nbsp;is&nbsp;the&nbsp;website&nbsp;operator's&nbsp;VAT&nbsp;number?</p>
<p><strong>Section&nbsp;21&nbsp;-&nbsp;Our&nbsp;details</strong></p>
<p>UK&nbsp;companies&nbsp;must&nbsp;provide&nbsp;their&nbsp;corporate&nbsp;names,&nbsp;their&nbsp;registration&nbsp;numbers,&nbsp;their&nbsp;place&nbsp;of&nbsp;registration&nbsp;and&nbsp;their&nbsp;registered&nbsp;office&nbsp;address&nbsp;on&nbsp;their&nbsp;websites&nbsp;(although&nbsp;not&nbsp;necessarily&nbsp;in&nbsp;this&nbsp;document).</p>
<p>Sole&nbsp;traders&nbsp;and&nbsp;partnerships&nbsp;that&nbsp;carry&nbsp;on&nbsp;a&nbsp;business&nbsp;in&nbsp;the&nbsp;UK&nbsp;under&nbsp;a&nbsp;"business&nbsp;name"&nbsp;(i.e.&nbsp;a&nbsp;name&nbsp;which&nbsp;is&nbsp;not&nbsp;the&nbsp;name&nbsp;of&nbsp;the&nbsp;trader/names&nbsp;of&nbsp;the&nbsp;partners&nbsp;or&nbsp;certain&nbsp;other&nbsp;specified&nbsp;classes&nbsp;of&nbsp;name)&nbsp;must&nbsp;also&nbsp;make&nbsp;certain&nbsp;website&nbsp;disclosures:&nbsp;(i)&nbsp;in&nbsp;the&nbsp;case&nbsp;of&nbsp;a&nbsp;sole&nbsp;trader,&nbsp;the&nbsp;individual's&nbsp;name;&nbsp;(ii)&nbsp;in&nbsp;the&nbsp;case&nbsp;of&nbsp;a&nbsp;partnership,&nbsp;the&nbsp;name&nbsp;of&nbsp;each&nbsp;member&nbsp;of&nbsp;the&nbsp;partnership;&nbsp;and&nbsp;(iii)&nbsp;in&nbsp;either&nbsp;case,&nbsp;in&nbsp;relation&nbsp;to&nbsp;each&nbsp;person&nbsp;named,&nbsp;an&nbsp;address&nbsp;in&nbsp;the&nbsp;UK&nbsp;at&nbsp;which&nbsp;service&nbsp;of&nbsp;any&nbsp;document&nbsp;relating&nbsp;in&nbsp;any&nbsp;way&nbsp;to&nbsp;the&nbsp;business&nbsp;will&nbsp;be&nbsp;effective.&nbsp;All&nbsp;websites&nbsp;covered&nbsp;by&nbsp;the&nbsp;Electronic&nbsp;Commerce&nbsp;(EC&nbsp;Directive)&nbsp;Regulations&nbsp;2002&nbsp;must&nbsp;provide&nbsp;a&nbsp;geographic&nbsp;address&nbsp;(not&nbsp;a&nbsp;PO&nbsp;Box&nbsp;number)&nbsp;and&nbsp;an&nbsp;email&nbsp;address.&nbsp;All&nbsp;website&nbsp;operators&nbsp;covered&nbsp;by&nbsp;the&nbsp;Provision&nbsp;of&nbsp;Services&nbsp;Regulations&nbsp;2009&nbsp;must&nbsp;also&nbsp;provide&nbsp;a&nbsp;telephone&nbsp;number.</p>
<p><em>Section&nbsp;21.1</em></p>
<p>What&nbsp;is&nbsp;the&nbsp;name&nbsp;of&nbsp;the&nbsp;company,&nbsp;partnership,&nbsp;individual&nbsp;or&nbsp;other&nbsp;legal&nbsp;person&nbsp;or&nbsp;entity&nbsp;that&nbsp;owns&nbsp;and&nbsp;operates&nbsp;the&nbsp;website?</p>
<p><em>Section&nbsp;21.2</em></p>
<p>Is&nbsp;the&nbsp;website&nbsp;operator&nbsp;a&nbsp;company?</p>
<p>In&nbsp;what&nbsp;jurisdiction&nbsp;is&nbsp;the&nbsp;website&nbsp;operator&nbsp;registered?&nbsp;What&nbsp;is&nbsp;the&nbsp;website&nbsp;operator's&nbsp;company&nbsp;registration&nbsp;number&nbsp;or&nbsp;equivalent?&nbsp;What&nbsp;is&nbsp;the&nbsp;website&nbsp;operator's&nbsp;registered&nbsp;address?</p>
<p><em>Section&nbsp;21.3</em></p>
<p>Where&nbsp;is&nbsp;the&nbsp;website&nbsp;operator's&nbsp;head&nbsp;office&nbsp;or&nbsp;principal&nbsp;place&nbsp;of&nbsp;business?</p>
<p><em>Section&nbsp;21.4</em></p>
<p>What&nbsp;is&nbsp;the&nbsp;website&nbsp;operator's&nbsp;contact&nbsp;email&nbsp;address?&nbsp;What&nbsp;is&nbsp;the&nbsp;website&nbsp;operator's&nbsp;contact&nbsp;telephone&nbsp;number?</p>
</div>
<?php include 'usr_footer.php';?>